/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Banknote, Bird, CircleDollarSign, Gauge, RefreshCw, ShieldCheck, Target, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, XAxis, YAxis } from "recharts";

import { useFarmScope } from "@/components/farm-scope-context";
import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from "@/components/ui/chart";

type Metric = { value: number | null; previous: number | null; target: number | null; confidence: "actual" | "estimate" | "unavailable" };
type DashboardData = {
  meta: { dateFrom:string; dateTo:string; refreshedAt:string; recordCoverage:number; calculationCompleteness:number; latestRecordAt:string|null; financialStatus:string };
  scorecard: { revenue:Metric; profit:Metric; collection:Metric; hdep:Metric; mortality:Metric; actions:Metric };
  operations: { trends:Array<{date:string;eggs:number;hdep:number|null;mortality:number|null;feedPerBirdGrams:number|null}>; liveBirds:number;activeFlocks:number;activeFarms:number;activeHouses:number;capacityUtilization:number|null; eggs:number; normalEggs:number;brokenEggs:number;dirtyEggs:number;feedKg:number;feedLeftoverKg:number;waterLiters:number;hdep:number|null;mortality:number|null;feedPerBirdGrams:number|null;layerFcr:number|null;waterFeedRatio:number|null;marketableRate:number|null;upcomingVaccinations:number };
  financials: { revenue:number;paid:number;receivables:number;collectionRate:number|null;estimatedCost:number;profit:number|null;margin:number|null;confidence:string;mix:Array<{label:string;value:number}> };
  commercial: { companyWide:boolean;totalLeads:number;staleLeads:number;conversionRate:number|null;openOrders:number;pipelineValue:number };
  rankings: { farms:Array<{id:string;label:string;revenue:number;cost:number;profit:number;margin:number|null}> };
  alerts:Array<{severity:"high"|"medium"|"low";title:string;context:string;route:string}>;
};

const charts = { hdep:{label:"HDEP %",color:"var(--chart-1)"},mortality:{label:"Mortality %",color:"var(--chart-4)"},eggs:{label:"Eggs",color:"var(--chart-2)"},value:{label:"Revenue",color:"var(--chart-1)"} } satisfies ChartConfig;
const money = (value:number|null) => value === null ? "Unavailable" : new Intl.NumberFormat("en-US",{style:"currency",currency:"ETB",maximumFractionDigits:0}).format(value);
const number = (value:number|null, suffix="") => value === null ? "Unavailable" : `${value.toLocaleString(undefined,{maximumFractionDigits:2})}${suffix}`;
const labelize = (value:string) => value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());

function Delta({metric,inverse=false}:{metric:Metric;inverse?:boolean}) {
  if (metric.value === null || metric.previous === null) return <span className="text-forest-500">No comparison</span>;
  const delta = metric.value - metric.previous;
  const positive = inverse ? delta <= 0 : delta >= 0;
  return <span className={`inline-flex items-center gap-1 ${positive?"text-leaf-500":"text-ember-500"}`}>{delta>=0?<TrendingUp className="h-3.5 w-3.5"/>:<TrendingDown className="h-3.5 w-3.5"/>}{Math.abs(delta).toLocaleString(undefined,{maximumFractionDigits:1})} vs prior</span>;
}

function ScoreCard({title,metric,format,icon:Icon,href,inverse=false}:{title:string;metric:Metric;format:(v:number|null)=>string;icon:typeof Banknote;href:string;inverse?:boolean}) {
  const badge = metric.confidence === "actual" ? "Actual" : metric.confidence === "estimate" ? "Estimate" : "Unavailable";
  return <Link href={href} className="group rounded-2xl border border-sand-200 bg-white p-4 shadow-sm outline-none transition hover:border-forest-500/40 hover:shadow-md focus-visible:ring-2 focus-visible:ring-forest-700">
    <div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-sand-100 text-forest-700"><Icon className="h-5 w-5"/></span><span className={`rounded-full px-2 py-1 text-[11px] font-medium ${metric.confidence==="unavailable"?"bg-sand-100 text-forest-600":metric.confidence==="estimate"?"bg-amber-500/10 text-amber-800":"bg-leaf-500/10 text-leaf-500"}`}>{badge}</span></div>
    <p className="mt-4 text-xs font-medium uppercase tracking-[0.14em] text-forest-500">{title}</p><p className="mt-1 text-2xl font-semibold tabular-nums text-forest-900">{format(metric.value)}</p>
    <p className="mt-2 text-xs"><Delta metric={metric} inverse={inverse}/></p>
    {metric.target!==null?<p className="mt-1 text-xs text-forest-600">Target {format(metric.target)}</p>:null}
  </Link>;
}

function Skeleton() { return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3" aria-label="Loading executive dashboard">{Array.from({length:6}).map((_,i)=><div key={i} className="h-44 animate-pulse rounded-2xl border border-sand-200 bg-white"><div className="m-5 h-4 w-24 rounded bg-sand-100"/><div className="m-5 h-9 w-36 rounded bg-sand-100"/></div>)}</div>; }

export function ExecutiveControlTower() {
  const {scope,period,branches,farms,houses,flocks,batches} = useFarmScope();
  const [data,setData]=useState<DashboardData|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const scopeLabel=useMemo(()=>[
    branches.find(x=>x.id===scope.branchId)?.name,farms.find(x=>x.id===scope.farmId)?.name,houses.find(x=>x.id===scope.houseId)?.name,
    flocks.find(x=>x.id===scope.flockId)?.flock_code,batches.find(x=>x.id===scope.batchId)?.batch_code
  ].filter(Boolean).join(" / ")||"All operations",[scope,branches,farms,houses,flocks,batches]);
  const load=async(signal?:AbortSignal)=>{setLoading(true);setError(null);const p=new URLSearchParams({date_from:period.dateFrom,date_to:period.dateTo,branch_id:scope.branchId,farm_id:scope.farmId,house_id:scope.houseId,flock_id:scope.flockId,batch_id:scope.batchId});const response=await fetch(`/api/ceo/dashboard?${p}`,{signal});const body=await response.json();if(!response.ok)throw new Error(body?.error??"Could not load the executive dashboard.");setData(body);setLoading(false);};
  useEffect(()=>{const controller=new AbortController();void load(controller.signal).catch(err=>{if(err instanceof DOMException&&err.name==="AbortError")return;setError(err instanceof Error?err.message:"Could not load dashboard");setLoading(false);});return()=>controller.abort();},[period.dateFrom,period.dateTo,scope.branchId,scope.farmId,scope.houseId,scope.flockId,scope.batchId]);
  return <div className="space-y-6">
    <section className="rounded-2xl border border-sand-200 bg-gradient-to-br from-forest-900 to-forest-700 p-5 text-sand-50 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.24em] text-sand-200">Executive command center</p><h1 className="mt-2 text-2xl font-semibold">Management control tower</h1><p className="mt-1 text-sm text-sand-100">{scopeLabel} · {period.dateFrom} to {period.dateTo}</p></div><button type="button" onClick={()=>void load().catch(err=>setError(String(err)))} disabled={loading} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-4 text-sm font-medium hover:bg-white/15 focus-visible:ring-2 focus-visible:ring-white disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Refresh</button></div>
      {data?<div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 border-t border-white/15 pt-4 text-xs text-sand-100"><span>Records {data.meta.recordCoverage}% complete</span><span>Core fields {data.meta.calculationCompleteness}% complete</span><span>Updated {new Date(data.meta.refreshedAt).toLocaleString()}</span></div>:null}
    </section>
    {error?<div role="alert" className="rounded-xl border border-ember-500/30 bg-ember-500/10 p-4 text-sm text-ember-500">{error} <button className="ml-2 underline" onClick={()=>void load()}>Retry</button></div>:null}
    {loading&&!data?<Skeleton/>:data?<>
      <section aria-labelledby="scorecard"><div className="mb-3 flex items-end justify-between"><div><h2 id="scorecard" className="text-lg font-semibold text-forest-900">Executive scorecard</h2><p className="text-sm text-forest-600">Outcome, efficiency, and risk signals for the selected scope.</p></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><ScoreCard title="Revenue" metric={data.scorecard.revenue} format={money} icon={Banknote} href="/app/sales"/><ScoreCard title="Operating profit" metric={data.scorecard.profit} format={money} icon={CircleDollarSign} href="/app/inventory"/><ScoreCard title="Cash collection" metric={data.scorecard.collection} format={v=>number(v,"%")} icon={WalletCards} href="/app/sales"/><ScoreCard title="Hen-day production" metric={data.scorecard.hdep} format={v=>number(v,"%")} icon={Gauge} href="/app/analytics"/><ScoreCard title="Cumulative mortality" metric={data.scorecard.mortality} format={v=>number(v,"%")} icon={Activity} href="/app/mortality" inverse/><ScoreCard title="Actions requiring review" metric={data.scorecard.actions} format={number} icon={AlertTriangle} href="/app/alerts" inverse/></div></section>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Live birds",number(data.operations.liveBirds),`${data.operations.activeFlocks} active flocks`,Bird],["Capacity",number(data.operations.capacityUtilization,"%"),`${data.operations.activeFarms} farms / ${data.operations.activeHouses} houses`,Gauge],["Feed / bird / day",number(data.operations.feedPerBirdGrams," g"),`${number(data.operations.feedKg," kg")} consumed`,Activity],["Layer FCR",number(data.operations.layerFcr),"kg feed / kg egg mass",Target],["Marketable eggs",number(data.operations.marketableRate,"%"),`${number(data.operations.normalEggs)} good eggs`,ShieldCheck]].map(([label,value,note,Icon])=><article key={String(label)} className="rounded-xl border border-sand-200 bg-white p-4"><Icon className="h-5 w-5 text-forest-600"/><p className="mt-3 text-xs uppercase tracking-[0.12em] text-forest-500">{String(label)}</p><p className="mt-1 text-xl font-semibold tabular-nums text-forest-900">{String(value)}</p><p className="mt-1 text-xs text-forest-600">{String(note)}</p></article>)}</section>
      <div className="grid gap-4 xl:grid-cols-[1.5fr_1fr]"><section className="rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><h2 className="text-base font-semibold text-forest-900">Production efficiency trend</h2><p className="text-sm text-forest-600">Daily HDEP and mortality use recorded birds at risk, not today’s flock count.</p><ChartContainer config={charts} className="mt-4 h-[280px] w-full"><AreaChart data={data.operations.trends}><CartesianGrid vertical={false} stroke="var(--sand-200)"/><XAxis dataKey="date" tickFormatter={v=>String(v).slice(5)} tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><ChartTooltip content={<ChartTooltipContent indicator="line"/>}/><Area type="monotone" dataKey="hdep" stroke="var(--color-hdep)" fill="var(--color-hdep)" fillOpacity={0.16} connectNulls/><Area type="monotone" dataKey="mortality" stroke="var(--color-mortality)" fill="var(--color-mortality)" fillOpacity={0.12} connectNulls/></AreaChart></ChartContainer><p className="sr-only">HDEP is {number(data.operations.hdep,"%")} and cumulative mortality is {number(data.operations.mortality,"%")}.</p></section>
      <section className="rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-base font-semibold text-forest-900">Management attention</h2><p className="text-sm text-forest-600">Highest-impact exceptions first.</p></div><Link href="/app/alerts" className="text-sm font-medium text-forest-700 underline-offset-4 hover:underline">All alerts</Link></div><div className="mt-4 space-y-3">{data.alerts.length?data.alerts.slice(0,5).map((alert,i)=><Link key={`${alert.title}-${i}`} href={alert.route} className="block rounded-xl border border-sand-200 bg-sand-50 p-3 focus-visible:ring-2 focus-visible:ring-forest-700"><div className="flex gap-2"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${alert.severity==="high"?"bg-ember-500":alert.severity==="medium"?"bg-amber-500":"bg-sky-500"}`}/><div><p className="text-sm font-medium text-forest-900">{alert.title}</p><p className="mt-1 text-xs text-forest-600">{alert.context}</p></div></div></Link>):<div className="rounded-xl bg-leaf-500/10 p-4 text-sm text-forest-700">No current exceptions for this scope.</div>}</div></section></div>
      <div className="grid gap-4 xl:grid-cols-2"><section className="rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><h2 className="text-base font-semibold text-forest-900">Farm profitability ranking</h2><p className="text-sm text-forest-600">Revenue less currently attributed costs; estimates are visibly identified.</p><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b border-sand-200 text-left text-xs uppercase tracking-wider text-forest-500"><th className="py-2">Farm</th><th>Revenue</th><th>Cost</th><th>Profit</th><th>Margin</th></tr></thead><tbody>{data.rankings.farms.length?data.rankings.farms.map(row=><tr key={row.id} className="border-b border-sand-100"><td className="py-3 font-medium text-forest-900">{row.label}</td><td>{money(row.revenue)}</td><td>{money(row.cost)}</td><td className={row.profit>=0?"text-leaf-500":"text-ember-500"}>{money(row.profit)}</td><td>{number(row.margin,"%")}</td></tr>):<tr><td colSpan={5} className="py-5 text-forest-600">No farm-linked sales in this period.</td></tr>}</tbody></table></div></section>
      <section className="rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><h2 className="text-base font-semibold text-forest-900">Commercial pulse</h2><p className="text-sm text-forest-600">Company-wide, independent of farm scope.</p></div><span className="h-fit rounded-full bg-sky-500/10 px-2.5 py-1 text-xs text-sky-500">Company-wide</span></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-sand-50 p-3"><p className="text-xs text-forest-500">Open pipeline</p><p className="mt-1 text-xl font-semibold">{money(data.commercial.pipelineValue)}</p><p className="text-xs text-forest-600">{data.commercial.openOrders} orders</p></div><div className="rounded-xl bg-sand-50 p-3"><p className="text-xs text-forest-500">Lead conversion</p><p className="mt-1 text-xl font-semibold">{number(data.commercial.conversionRate,"%")}</p><p className="text-xs text-forest-600">{data.commercial.totalLeads} total leads</p></div></div><h3 className="mt-5 text-sm font-medium text-forest-900">Revenue mix</h3><ChartContainer config={charts} className="mt-2 h-[150px] w-full"><BarChart data={data.financials.mix} layout="vertical"><CartesianGrid horizontal={false} stroke="var(--sand-200)"/><XAxis type="number" hide/><YAxis type="category" dataKey="label" width={110} tickFormatter={labelize} tickLine={false} axisLine={false}/><ChartTooltip content={<ChartTooltipContent/>}/><Bar dataKey="value" fill="var(--color-value)" radius={[0,6,6,0]}/></BarChart></ChartContainer></section></div>
      <section className="rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-semibold text-forest-900">Data trust and operational detail</h2><p className="text-sm text-forest-600">Missing inputs reduce confidence; they are never treated as zero.</p></div><Link href="/app/daily-records" className="rounded-xl bg-forest-900 px-4 py-2.5 text-sm font-medium text-white">Complete daily records</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-forest-500">Record coverage</p><p className="text-xl font-semibold">{number(data.meta.recordCoverage,"%")}</p></div><div><p className="text-xs text-forest-500">Core-field completeness</p><p className="text-xl font-semibold">{number(data.meta.calculationCompleteness,"%")}</p></div><div><p className="text-xs text-forest-500">Water / feed ratio</p><p className="text-xl font-semibold">{number(data.operations.waterFeedRatio," L/kg")}</p></div><div><p className="text-xs text-forest-500">Upcoming vaccines</p><p className="text-xl font-semibold">{number(data.operations.upcomingVaccinations)}</p></div></div></section>
    </>:null}
  </div>;
}
