/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowRight, Banknote, Bird, CheckCircle2, CircleDollarSign, Clock3, Gauge, MapPinned, RefreshCw, ShieldCheck, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, XAxis, YAxis } from "recharts";

import { useFarmScope } from "@/components/farm-scope-context";
import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from "@/components/ui/chart";

type Metric = { value:number|null; previous:number|null; target:number|null; confidence:"actual"|"estimate"|"unavailable" };
type Status = "critical"|"watch"|"data_gap"|"on_track";
type FarmPulse = { id:string;name:string;branchName:string;status:Status;liveBirds:number;activeFlocks:number;operatingHouses:number;totalHouses:number;capacityUtilization:number|null;recordsComplete:number;recordsExpected:number;feedClosed:number;feedExpected:number;eggs:number;hdep:number|null;mortality:number|null;feedPerBirdGrams:number|null;latestRecordAt:string|null;nextAction:string;actionRoute:string };
type BatchPulse = { id:string;code:string;source:string;status:Status;placementDate:string;ageDays:number;farmName:string;houseName:string;flocks:number;liveBirds:number;initialBirds:number;retentionPct:number|null;recordsComplete:number;recordsExpected:number;feedClosed:number;feedExpected:number;primaryLabel:string;primaryValue:number|null;primaryUnit:string;mortality:number|null;nextAction:string;actionRoute:string };
type DashboardData = {
  meta:{dateFrom:string;dateTo:string;refreshedAt:string;liveAsOf:string;recordCoverage:number;calculationCompleteness:number;latestRecordAt:string|null;financialStatus:string};
  live:{farms:FarmPulse[];batches:BatchPulse[];recordsComplete:number;recordsExpected:number;feedClosed:number;feedExpected:number;farmsNeedingAttention:number;batchesNeedingAttention:number};
  scorecard:{revenue:Metric;profit:Metric;collection:Metric;hdep:Metric;mortality:Metric;actions:Metric};
  operations:{trends:Array<{date:string;eggs:number;hdep:number|null;mortality:number|null;feedPerBirdGrams:number|null}>;liveBirds:number;activeFlocks:number;activeFarms:number;activeHouses:number;capacityUtilization:number|null;eggs:number;normalEggs:number;feedKg:number;hdep:number|null;mortality:number|null;feedPerBirdGrams:number|null;layerFcr:number|null;waterFeedRatio:number|null;marketableRate:number|null;upcomingVaccinations:number};
  financials:{revenue:number;paid:number;receivables:number;collectionRate:number|null;estimatedCost:number;profit:number|null;margin:number|null;confidence:string;mix:Array<{label:string;value:number}>};
  commercial:{companyWide:boolean;totalLeads:number;staleLeads:number;conversionRate:number|null;openOrders:number;pipelineValue:number};
  rankings:{farms:Array<{id:string;label:string;revenue:number;cost:number;profit:number;margin:number|null}>};
  alerts:Array<{severity:"high"|"medium"|"low";title:string;context:string;route:string}>;
};

const charts = { hdep:{label:"HDEP %",color:"var(--chart-1)"}, mortality:{label:"Mortality %",color:"var(--chart-4)"}, value:{label:"Revenue",color:"var(--chart-1)"} } satisfies ChartConfig;
const money = (value:number|null) => value === null ? "Unavailable" : new Intl.NumberFormat("en-US",{style:"currency",currency:"ETB",maximumFractionDigits:0}).format(value);
const number = (value:number|null,suffix="",digits=1) => value === null ? "Unavailable" : `${value.toLocaleString(undefined,{maximumFractionDigits:digits})}${suffix}`;
const labelize = (value:string) => value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const dateLabel = (value:string) => new Intl.DateTimeFormat("en-US",{timeZone:"Africa/Addis_Ababa",weekday:"long",month:"long",day:"numeric",year:"numeric"}).format(new Date(`${value}T12:00:00+03:00`));
const coverage = (done:number,total:number) => total > 0 ? Math.round(done/total*100) : 100;

const statusStyle:Record<Status,{label:string,dot:string,badge:string}> = {
  critical:{label:"Critical",dot:"bg-ember-500",badge:"bg-ember-500/10 text-ember-500"},
  watch:{label:"Watch",dot:"bg-amber-500",badge:"bg-amber-500/10 text-amber-800"},
  data_gap:{label:"Data gap",dot:"bg-sky-500",badge:"bg-sky-500/10 text-sky-600"},
  on_track:{label:"On track",dot:"bg-leaf-500",badge:"bg-leaf-500/10 text-leaf-600"},
};

function StatusBadge({status}:{status:Status}) { const style=statusStyle[status]; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.1em] ${style.badge}`}><span className={`h-1.5 w-1.5 rounded-full ${style.dot}`}/>{style.label}</span>; }
function Progress({value,tone="forest"}:{value:number;tone?:"forest"|"leaf"|"amber"}) { return <div className="h-1.5 overflow-hidden rounded-full bg-sand-100"><div className={`h-full rounded-full ${tone==="leaf"?"bg-leaf-500":tone==="amber"?"bg-amber-500":"bg-forest-600"}`} style={{width:`${Math.min(100,Math.max(value>0?3:0,value))}%`}}/></div>; }
function Delta({metric,inverse=false}:{metric:Metric;inverse?:boolean}) { if(metric.value===null||metric.previous===null)return <span className="text-forest-500">No prior comparison</span>;const delta=metric.value-metric.previous;const positive=inverse?delta<=0:delta>=0;return <span className={`inline-flex items-center gap-1 ${positive?"text-leaf-600":"text-ember-500"}`}>{delta>=0?<TrendingUp className="h-3.5 w-3.5"/>:<TrendingDown className="h-3.5 w-3.5"/>}{Math.abs(delta).toLocaleString(undefined,{maximumFractionDigits:1})} vs prior</span>; }

function ScoreCard({title,metric,format,icon:Icon,href,inverse=false}:{title:string;metric:Metric;format:(v:number|null)=>string;icon:typeof Banknote;href:string;inverse?:boolean}) { return <Link href={href} className="group min-w-[220px] flex-1 rounded-xl border border-sand-200 bg-white p-4 outline-none transition hover:-translate-y-0.5 hover:border-forest-500/40 hover:shadow-md focus-visible:ring-2 focus-visible:ring-forest-700"><div className="flex items-start justify-between"><Icon className="h-5 w-5 text-forest-600"/><span className={`rounded-full px-2 py-1 text-[10px] font-semibold uppercase tracking-wide ${metric.confidence==="unavailable"?"bg-sand-100 text-forest-500":metric.confidence==="estimate"?"bg-amber-500/10 text-amber-800":"bg-leaf-500/10 text-leaf-600"}`}>{metric.confidence}</span></div><p className="mt-4 text-[10px] font-semibold uppercase tracking-[.16em] text-forest-500">{title}</p><p className="mt-1 font-display text-2xl font-semibold tabular-nums text-forest-900">{format(metric.value)}</p><p className="mt-2 text-[11px]"><Delta metric={metric} inverse={inverse}/></p></Link>; }
function Skeleton() { return <div className="space-y-4" aria-label="Loading command center"><div className="h-56 animate-pulse rounded-2xl bg-forest-900"/><div className="grid gap-4 lg:grid-cols-2">{[0,1].map(i=><div key={i} className="h-80 animate-pulse rounded-2xl border border-sand-200 bg-white"/>)}</div></div>; }

function FarmBoard({farms}:{farms:FarmPulse[]}) {
  return <section className="min-w-0 overflow-hidden rounded-2xl border border-sand-200 bg-white shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-sand-200 bg-[#f2eee4] p-5"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-forest-500">Live operating map</p><h2 className="mt-1 font-display text-2xl font-semibold text-forest-900">Farm pulse board</h2><p className="mt-1 text-sm text-forest-600">Attention-first view of birds, production, records, and feeding closure.</p></div><Link href="/app/farms" className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-sand-300 bg-white px-3 text-xs font-semibold text-forest-700">Open farm monitoring<ArrowRight className="h-4 w-4"/></Link></div>
    {farms.length?<div className="divide-y divide-sand-100">{farms.map(farm=><article key={farm.id} className="grid gap-4 p-5 transition hover:bg-sand-50/70 xl:grid-cols-[1.15fr_.95fr_.85fr_auto]"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href={`/app/farms/${farm.id}`} className="truncate font-semibold text-forest-900 underline decoration-sand-200 underline-offset-4 hover:decoration-forest-700">{farm.name}</Link><StatusBadge status={farm.status}/></div><p className="mt-1 text-xs text-forest-500">{farm.branchName} · {farm.activeFlocks} flocks across {farm.operatingHouses}/{farm.totalHouses} houses</p><p className="mt-2 font-display text-2xl font-semibold tabular-nums text-forest-900">{farm.liveBirds.toLocaleString()} <span className="font-sans text-xs font-normal text-forest-500">live birds</span></p></div>
      <div><div className="flex items-center justify-between text-xs"><span className="text-forest-500">Capacity</span><strong>{number(farm.capacityUtilization,"%",0)}</strong></div><Progress value={farm.capacityUtilization??0}/><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><span className="block text-forest-500">Eggs</span><strong>{farm.recordsComplete?farm.eggs.toLocaleString():"—"}</strong></div><div><span className="block text-forest-500">HDEP</span><strong>{number(farm.hdep,"%")}</strong></div><div><span className="block text-forest-500">Mortality</span><strong className={farm.mortality!==null&&farm.mortality>=2?"text-ember-500":""}>{number(farm.mortality,"%",2)}</strong></div></div></div>
      <div className="space-y-3"><div><div className="mb-1 flex justify-between text-[11px]"><span className="text-forest-500">Daily records</span><strong>{farm.recordsComplete}/{farm.recordsExpected}</strong></div><Progress value={coverage(farm.recordsComplete,farm.recordsExpected)} tone={farm.recordsComplete===farm.recordsExpected?"leaf":"amber"}/></div><div><div className="mb-1 flex justify-between text-[11px]"><span className="text-forest-500">Feed days closed</span><strong>{farm.feedClosed}/{farm.feedExpected}</strong></div><Progress value={coverage(farm.feedClosed,farm.feedExpected)} tone={farm.feedClosed===farm.feedExpected?"leaf":"amber"}/></div><p className="text-[11px] text-forest-500">Feed / bird {number(farm.feedPerBirdGrams," g")}</p></div>
      <Link href={farm.actionRoute} aria-label={`Inspect ${farm.name}: ${farm.nextAction}`} className="inline-flex min-h-10 items-center justify-between gap-3 self-center rounded-xl border border-sand-200 px-3 text-xs font-semibold text-forest-700 hover:border-forest-500 xl:w-52"><span><span className="block text-[9px] uppercase tracking-[.12em] text-forest-500">Manager follow-up</span>{farm.nextAction}</span><ArrowRight className="h-4 w-4 shrink-0"/></Link></article>)}</div>:<div className="p-8 text-center text-sm text-forest-600">No active farms match the selected scope.</div>}
  </section>;
}

function BatchBoard({batches}:{batches:BatchPulse[]}) {
  return <section className="min-w-0 overflow-hidden rounded-2xl border border-sand-200 bg-white shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-sand-200 p-5"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-forest-500">Bird-cycle continuity</p><h2 className="mt-1 font-display text-2xl font-semibold text-forest-900">Active batch runway</h2><p className="mt-1 text-sm text-forest-600">Age, retention, daily evidence, and the next operating move.</p></div><Link href="/app/batches" className="text-xs font-semibold text-forest-700 underline underline-offset-4">Manage batches</Link></div>
    {batches.length?<div className="w-full max-w-full overflow-x-auto overscroll-x-contain"><div className="flex w-max gap-3 p-4">{batches.map(batch=><article key={batch.id} className="w-[320px] shrink-0 rounded-xl border border-sand-200 bg-sand-50 p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-[10px] uppercase tracking-[.14em] text-forest-500">{batch.farmName} · {batch.houseName}</p><h3 className="mt-1 font-semibold text-forest-900">{batch.code}</h3></div><StatusBadge status={batch.status}/></div><div className="mt-4 grid grid-cols-3 gap-2 border-y border-sand-200 py-3 text-xs"><div><span className="block text-forest-500">Cycle age</span><strong>Day {batch.ageDays}</strong></div><div><span className="block text-forest-500">Live birds</span><strong>{batch.liveBirds.toLocaleString()}</strong></div><div><span className="block text-forest-500">Retention</span><strong>{number(batch.retentionPct,"%")}</strong></div></div><div className="mt-4 flex items-end justify-between"><div><span className="text-[11px] text-forest-500">{batch.primaryLabel}</span><p className="font-display text-xl font-semibold text-forest-900">{number(batch.primaryValue,batch.primaryUnit)}</p></div><span className="text-[11px] text-forest-500">Mortality {number(batch.mortality,"%",2)}</span></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-lg bg-white p-2.5 text-[11px]"><span className="text-forest-500">Records received</span><strong className="block text-forest-900">{batch.recordsComplete}/{batch.recordsExpected} flocks</strong></div><div className="rounded-lg bg-white p-2.5 text-[11px]"><span className="text-forest-500">Feed days closed</span><strong className="block text-forest-900">{batch.feedClosed}/{batch.feedExpected} flocks</strong></div></div><div className={`mt-4 rounded-lg border p-3 ${batch.status==="on_track"?"border-leaf-500/25 bg-leaf-500/10":"border-amber-500/30 bg-amber-500/10"}`}><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-forest-500">Operational status</p><p className="mt-1 text-xs font-semibold text-forest-900">{batch.nextAction}</p><Link href={batch.actionRoute} aria-label={`Inspect ${batch.code}: ${batch.nextAction}`} className="mt-2 inline-flex items-center gap-1 text-[11px] font-semibold text-forest-700 underline underline-offset-4">Inspect evidence<ArrowRight className="h-3.5 w-3.5"/></Link></div></article>)}</div></div>:<div className="p-8 text-center text-sm text-forest-600">No active batches match the selected scope.</div>}
  </section>;
}

export function ExecutiveControlTower() {
  const {scope,period,branches,farms,houses,flocks,batches}=useFarmScope();
  const [data,setData]=useState<DashboardData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
  const scopeLabel=useMemo(()=>[branches.find(x=>x.id===scope.branchId)?.name,farms.find(x=>x.id===scope.farmId)?.name,houses.find(x=>x.id===scope.houseId)?.name,flocks.find(x=>x.id===scope.flockId)?.flock_code,batches.find(x=>x.id===scope.batchId)?.batch_code].filter(Boolean).join(" / ")||"Company-wide operations",[scope,branches,farms,houses,flocks,batches]);
  const load=async(signal?:AbortSignal)=>{setLoading(true);setError(null);const p=new URLSearchParams({date_from:period.dateFrom,date_to:period.dateTo,branch_id:scope.branchId,farm_id:scope.farmId,house_id:scope.houseId,flock_id:scope.flockId,batch_id:scope.batchId});const response=await fetch(`/api/ceo/dashboard?${p}`,{signal});const body=await response.json();if(!response.ok)throw new Error(body?.error??"Could not load the command center.");setData(body);setLoading(false);};
  useEffect(()=>{const controller=new AbortController();void load(controller.signal).catch(err=>{if(err instanceof DOMException&&err.name==="AbortError")return;setError(err instanceof Error?err.message:"Could not load dashboard");setLoading(false);});return()=>controller.abort();},[period.dateFrom,period.dateTo,scope.branchId,scope.farmId,scope.houseId,scope.flockId,scope.batchId]);
  return <div className="min-w-0 space-y-6">
    <section className="relative overflow-hidden rounded-2xl border border-forest-700 bg-forest-900 p-6 text-sand-50 shadow-sm"><div aria-hidden className="absolute -right-16 -top-20 h-60 w-60 rounded-full border-[34px] border-amber-500/10"/><div className="relative grid gap-6 xl:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-2 rounded-full bg-leaf-500/15 px-3 py-1 text-[10px] font-semibold uppercase tracking-[.18em] text-sand-100"><span className="h-2 w-2 animate-pulse rounded-full bg-leaf-500"/>Live command center</span><span className="text-xs text-sand-200">Africa/Addis Ababa</span></div><h1 className="mt-4 max-w-3xl font-display text-3xl font-semibold leading-tight sm:text-4xl">See the whole operation before deciding where to act.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-sand-100">{scopeLabel} · Live state for {data?dateLabel(data.meta.liveAsOf):"today"}. Financial comparisons use {period.dateFrom} to {period.dateTo}.</p></div><div className="flex flex-col items-start gap-3 xl:items-end"><button type="button" onClick={()=>void load().catch(err=>setError(String(err)))} disabled={loading} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-4 text-sm font-semibold hover:bg-white/15 focus-visible:ring-2 focus-visible:ring-white disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Refresh live picture</button>{data?<p className="text-xs text-sand-200">Updated {new Date(data.meta.refreshedAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</p>:null}</div></div>
      {data?<div className="relative mt-6 grid gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10 sm:grid-cols-2 xl:grid-cols-5">{[["Live birds",data.operations.liveBirds.toLocaleString(),`${data.operations.activeFlocks} active flocks`,Bird],["Farms requiring action",String(data.live.farmsNeedingAttention),`${data.operations.activeFarms} active farms`,MapPinned],["Records received",`${data.live.recordsComplete}/${data.live.recordsExpected}`,`${coverage(data.live.recordsComplete,data.live.recordsExpected)}% of today's flock records`,CheckCircle2],["Feeding days closed",`${data.live.feedClosed}/${data.live.feedExpected}`,`${coverage(data.live.feedClosed,data.live.feedExpected)}% closed`,Clock3],["Open management actions",number(data.scorecard.actions.value),"Prioritized below",AlertTriangle]].map(([label,value,note,Icon])=><div key={String(label)} className="bg-forest-900/80 p-4"><Icon className="h-4 w-4 text-amber-400"/><p className="mt-3 text-[10px] font-semibold uppercase tracking-[.15em] text-sand-200">{String(label)}</p><p className="mt-1 font-display text-2xl font-semibold tabular-nums">{String(value)}</p><p className="mt-1 text-[11px] text-sand-200">{String(note)}</p></div>)}</div>:null}
    </section>
    {error?<div role="alert" className="rounded-xl border border-ember-500/30 bg-ember-500/10 p-4 text-sm text-ember-500">{error} <button className="ml-2 underline" onClick={()=>void load()}>Retry</button></div>:null}
    {loading&&!data?<Skeleton/>:data?<>
      <FarmBoard farms={data.live.farms}/>
      <BatchBoard batches={data.live.batches}/>
      <section aria-labelledby="outcome-scorecard"><div className="mb-3"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-forest-500">Business outcomes</p><h2 id="outcome-scorecard" className="mt-1 font-display text-2xl font-semibold text-forest-900">Executive scorecard</h2><p className="mt-1 text-sm text-forest-600">Period results remain visible without displacing today’s operating picture.</p></div><div className="max-w-full overflow-x-auto overscroll-x-contain"><div className="flex min-w-max gap-3 pb-1"><ScoreCard title="Revenue" metric={data.scorecard.revenue} format={money} icon={Banknote} href="/app/sales"/><ScoreCard title="Operating profit" metric={data.scorecard.profit} format={money} icon={CircleDollarSign} href="/app/inventory"/><ScoreCard title="Cash collection" metric={data.scorecard.collection} format={v=>number(v,"%")} icon={WalletCards} href="/app/sales"/><ScoreCard title="Hen-day production" metric={data.scorecard.hdep} format={v=>number(v,"%")} icon={Gauge} href="/app/analytics"/><ScoreCard title="Mortality" metric={data.scorecard.mortality} format={v=>number(v,"%")} icon={Activity} href="/app/mortality" inverse/></div></div></section>
      <div className="grid min-w-0 gap-4 xl:grid-cols-[1.45fr_1fr]"><section className="min-w-0 overflow-hidden rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-forest-500">Performance trajectory</p><h2 className="mt-1 font-display text-xl font-semibold text-forest-900">Production and mortality trend</h2><p className="mt-1 text-sm text-forest-600">HDEP and mortality use recorded birds at risk; gaps remain unavailable.</p></div><Link href="/app/analytics" className="text-xs font-semibold text-forest-700 underline underline-offset-4">Deep analytics</Link></div><div className="mt-4 w-full overflow-x-auto"><ChartContainer config={charts} className="h-[280px] min-w-[680px]"><AreaChart data={data.operations.trends}><CartesianGrid vertical={false} stroke="var(--sand-200)"/><XAxis dataKey="date" tickFormatter={v=>String(v).slice(5)} tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><ChartTooltip content={<ChartTooltipContent indicator="line"/>}/><Area type="monotone" dataKey="hdep" stroke="var(--color-hdep)" fill="var(--color-hdep)" fillOpacity={0.14} connectNulls/><Area type="monotone" dataKey="mortality" stroke="var(--color-mortality)" fill="var(--color-mortality)" fillOpacity={0.1} connectNulls/></AreaChart></ChartContainer></div></section>
        <section className="rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-forest-500">Decision queue</p><h2 className="mt-1 font-display text-xl font-semibold text-forest-900">Management attention</h2><p className="mt-1 text-sm text-forest-600">Highest-impact exceptions first.</p></div><Link href="/app/alerts" className="text-xs font-semibold text-forest-700 underline underline-offset-4">All alerts</Link></div><div className="mt-4 space-y-3">{data.alerts.length?data.alerts.slice(0,5).map((alert,i)=><Link key={`${alert.title}-${i}`} href={alert.route} className="block rounded-xl border border-sand-200 bg-sand-50 p-3 outline-none transition hover:border-forest-400 focus-visible:ring-2 focus-visible:ring-forest-700"><div className="flex gap-3"><span className={`mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full ${alert.severity==="high"?"bg-ember-500":alert.severity==="medium"?"bg-amber-500":"bg-sky-500"}`}/><div><p className="text-sm font-semibold text-forest-900">{alert.title}</p><p className="mt-1 text-xs leading-5 text-forest-600">{alert.context}</p></div></div></Link>):<div className="rounded-xl bg-leaf-500/10 p-4 text-sm text-forest-700"><CheckCircle2 className="mb-2 h-5 w-5"/>No current exceptions for this scope.</div>}</div></section></div>
      <div className="grid min-w-0 gap-4 xl:grid-cols-2"><section className="min-w-0 overflow-hidden rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-forest-500">Economic comparison</p><h2 className="mt-1 font-display text-xl font-semibold text-forest-900">Farm profitability</h2></div><span className="text-[11px] text-amber-800">Attributed-cost estimate</span></div><div className="mt-4 overflow-x-auto"><table className="min-w-[620px] w-full text-sm"><thead><tr className="border-b border-sand-200 text-left text-[10px] uppercase tracking-[.14em] text-forest-500"><th className="py-2">Farm</th><th>Revenue</th><th>Cost</th><th>Profit</th><th>Margin</th></tr></thead><tbody>{data.rankings.farms.length?data.rankings.farms.map(row=><tr key={row.id} className="border-b border-sand-100"><td className="py-3 font-semibold text-forest-900">{row.label}</td><td>{money(row.revenue)}</td><td>{money(row.cost)}</td><td className={row.profit>=0?"text-leaf-600":"text-ember-500"}>{money(row.profit)}</td><td>{number(row.margin,"%")}</td></tr>):<tr><td colSpan={5} className="py-5 text-forest-600">No farm-linked sales in this period.</td></tr>}</tbody></table></div></section>
        <section className="min-w-0 overflow-hidden rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-forest-500">Commercial horizon</p><h2 className="mt-1 font-display text-xl font-semibold text-forest-900">Sales pipeline pulse</h2></div><span className="h-fit rounded-full bg-sky-500/10 px-2.5 py-1 text-[10px] font-semibold text-sky-600">Company-wide</span></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-sand-50 p-3"><p className="text-xs text-forest-500">Open pipeline</p><p className="mt-1 font-display text-xl font-semibold">{money(data.commercial.pipelineValue)}</p><p className="text-xs text-forest-600">{data.commercial.openOrders} orders</p></div><div className="rounded-xl bg-sand-50 p-3"><p className="text-xs text-forest-500">Lead conversion</p><p className="mt-1 font-display text-xl font-semibold">{number(data.commercial.conversionRate,"%")}</p><p className="text-xs text-forest-600">{data.commercial.staleLeads} stale leads</p></div></div><div className="mt-3 w-full overflow-x-auto"><ChartContainer config={charts} className="h-[150px] min-w-[440px]"><BarChart data={data.financials.mix} layout="vertical"><CartesianGrid horizontal={false} stroke="var(--sand-200)"/><XAxis type="number" hide/><YAxis type="category" dataKey="label" width={110} tickFormatter={labelize} tickLine={false} axisLine={false}/><ChartTooltip content={<ChartTooltipContent/>}/><Bar dataKey="value" fill="var(--color-value)" radius={[0,6,6,0]}/></BarChart></ChartContainer></div></section></div>
      <section className="rounded-2xl border border-sand-200 bg-[#f2eee4] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-forest-700"><ShieldCheck className="h-5 w-5"/></span><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-forest-500">Decision confidence</p><h2 className="mt-1 font-display text-xl font-semibold text-forest-900">Data trust</h2><p className="mt-1 text-sm text-forest-600">Missing inputs reduce confidence and are never silently treated as zero. Farm teams own operational entry; this view monitors completion.</p></div></div><Link href="/app/daily-records" className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-forest-900 px-4 text-xs font-semibold text-white">Inspect record coverage<ArrowRight className="h-4 w-4"/></Link></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Period record coverage",number(data.meta.recordCoverage,"%")],["Core-field completeness",number(data.meta.calculationCompleteness,"%")],["Water / feed ratio",number(data.operations.waterFeedRatio," L/kg")],["Upcoming vaccines",number(data.operations.upcomingVaccinations)]].map(([label,value])=><div key={label} className="rounded-xl bg-white p-3"><p className="text-xs text-forest-500">{label}</p><p className="mt-1 font-display text-xl font-semibold text-forest-900">{value}</p></div>)}</div></section>
    </>:null}
  </div>;
}
