export type ReconciliationDomain="birds"|"feed"|"mortality"|"eggs_sales"|"inventory"|"financial"|"lineage"|"governance";
export type ReconciliationSeverity="critical"|"high"|"medium"|"low";
export type Evidence=Record<string,unknown>;

export type FindingDraft={fingerprint:string;ruleCode:string;domain:ReconciliationDomain;severity:ReconciliationSeverity;title:string;explanation:string;recommendedAction:string;branchId?:string|null;farmId?:string|null;houseId?:string|null;flockId?:string|null;batchId?:string|null;warehouseId?:string|null;recordDate?:string|null;expectedValue?:number|null;recordedValue?:number|null;variance?:number|null;unit?:string|null;estimatedImpactEtb?:number|null;evidence:Evidence};
export type DailyInput={id:string;flockId:string;recordDate:string;openingBirds:number|null;closingBirds:number|null;deaths:number|null;culls:number;transfersIn:number;transfersOut:number;otherRemovals:number;totalEggs:number|null;normalEggs:number|null;brokenEggs:number|null;dirtyEggs:number|null;feedKg:number|null;updatedAt:string;recordedBy:string|null};
export type FlockInput={id:string;code:string;status:string;farmId:string;houseId:string;batchId:string|null;placementDate:string;initialCount:number;currentCount:number};
export type FarmInput={id:string;branchId:string;name:string};
export type HouseInput={id:string;farmId:string;name:string};
export type BatchInput={id:string;farmId:string;houseId:string;totalCount:number;status:string;code:string};
export type FeedClosureInput={id:string;flockId:string;recordDate:string;actualKg:number;status:string};
export type FeedSessionInput={id:string;flockId:string;recordDate:string;actualKg:number|null;status:string};
export type StockInput={id:string;warehouseId:string;itemId:string;flockId:string|null;transactionType:string;quantity:number;unitCost:number;sourceKind:string|null;sourceKey:string|null;transactionDate:string;recordedBy:string|null};
export type MortalityInput={id:string;flockId:string;recordDate:string;count:number};
export type SaleInput={id:string;flockId:string|null;farmId:string|null;saleDate:string;category:string;label:string;quantity:number;unit:string;grossAmount:number;customer:string|null;createdAt:string;recordedBy:string|null};
export type ConversionInput={category:string;unit:string;multiplier:number};
export type PhysicalCountInput={id:string;warehouseId:string;itemId:string;countDate:string;ledgerQuantity:number;countedQuantity:number;unitCost:number;countedBy:string};
export type WarehouseInput={id:string;name:string};
export type CostEntryInput={id:string;amount:number;entryDate:string;category:string;description:string;allocationMethod:string;supplierName:string|null;invoiceNumber:string|null;farmId:string|null;flockId:string|null;batchId:string|null};
export type CostAllocationInput={id:string;costEntryId:string;amount:number};
export type CostPeriodInput={id:string;periodStart:string;periodEnd:string;status:string;unallocatedCost:number;warnings:unknown;farmId:string|null;flockId:string|null;batchId:string|null};
export type OperatingDayInput={farmId:string;date:string;status:string;lockedAt:string|null};

export type ReconciliationInput={asOfDate:string;daily:DailyInput[];flocks:FlockInput[];farms:FarmInput[];houses:HouseInput[];batches:BatchInput[];closures:FeedClosureInput[];sessions:FeedSessionInput[];stock:StockInput[];mortality:MortalityInput[];sales:SaleInput[];conversions:ConversionInput[];physicalCounts:PhysicalCountInput[];warehouses:WarehouseInput[];costEntries:CostEntryInput[];costAllocations:CostAllocationInput[];costPeriods:CostPeriodInput[];operatingDays:OperatingDayInput[];approvedCorrectionSourceIds:Set<string>};

const severityRank:Record<ReconciliationSeverity,number>={critical:4,high:3,medium:2,low:1};
const round=(value:number,digits=3)=>Number(value.toFixed(digits));
const dateDiff=(a:string,b:string)=>Math.round((Date.parse(`${a}T00:00:00Z`)-Date.parse(`${b}T00:00:00Z`))/86400000);
const abs=(value:number)=>Math.abs(value);
const meaningful=(value:number,baseline:number)=>abs(value)>=Math.max(2,abs(baseline)*.005);
const scope=(flock:FlockInput|undefined,farms:Map<string,FarmInput>)=>({flockId:flock?.id??null,farmId:flock?.farmId??null,houseId:flock?.houseId??null,batchId:flock?.batchId??null,branchId:flock?farms.get(flock.farmId)?.branchId??null:null});

export function evaluateOperationalReconciliation(input:ReconciliationInput):FindingDraft[]{
  const findings=new Map<string,FindingDraft>();
  const add=(finding:FindingDraft)=>{const prior=findings.get(finding.fingerprint);if(!prior||severityRank[finding.severity]>severityRank[prior.severity])findings.set(finding.fingerprint,finding)};
  const flockById=new Map(input.flocks.map(row=>[row.id,row]));const farmById=new Map(input.farms.map(row=>[row.id,row]));const houseById=new Map(input.houses.map(row=>[row.id,row]));const batchById=new Map(input.batches.map(row=>[row.id,row]));
  const dailyByFlock=new Map<string,DailyInput[]>();for(const row of input.daily)dailyByFlock.set(row.flockId,[...(dailyByFlock.get(row.flockId)??[]),row]);for(const rows of dailyByFlock.values())rows.sort((a,b)=>a.recordDate.localeCompare(b.recordDate));
  const mortalityByDay=new Map<string,number>();for(const row of input.mortality){const key=`${row.flockId}:${row.recordDate}`;mortalityByDay.set(key,(mortalityByDay.get(key)??0)+row.count)}

  for(const row of input.daily){const flock=flockById.get(row.flockId);const common={...scope(flock,farmById),recordDate:row.recordDate};
    if(row.openingBirds===null||row.closingBirds===null)add({fingerprint:`bird-counts:${row.id}`,ruleCode:"BIRD_DAY_COUNTS_MISSING",domain:"birds",severity:"medium",title:`Bird custody is incomplete for ${flock?.code??"a flock"}`,explanation:"Opening and closing bird counts are required before losses and movements can be reconciled.",recommendedAction:"Complete the Daily Record bird counts or submit a locked-record correction.",...common,evidence:{dailyRecordId:row.id,openingBirds:row.openingBirds,closingBirds:row.closingBirds,recordedBy:row.recordedBy}});
    if(row.openingBirds!==null&&row.closingBirds!==null){const expected=row.openingBirds+row.transfersIn-(row.deaths??0)-row.culls-row.transfersOut-row.otherRemovals;const variance=row.closingBirds-expected;if(variance!==0)add({fingerprint:`bird-equation:${row.id}`,ruleCode:"BIRD_DAY_IMBALANCE",domain:"birds",severity:meaningful(variance,row.openingBirds)?"high":"medium",title:`Bird ledger does not balance for ${flock?.code??"a flock"}`,explanation:`The closing count differs from the movement equation by ${abs(variance)} bird${abs(variance)===1?"":"s"}.`,recommendedAction:"Verify deaths, culls, transfers, removals, and the physical closing count.",...common,expectedValue:expected,recordedValue:row.closingBirds,variance,unit:"birds",evidence:{dailyRecordId:row.id,openingBirds:row.openingBirds,deaths:row.deaths,culls:row.culls,transfersIn:row.transfersIn,transfersOut:row.transfersOut,otherRemovals:row.otherRemovals,recordedBy:row.recordedBy}})}
    if(row.totalEggs!==null&&row.normalEggs!==null&&row.brokenEggs!==null&&row.dirtyEggs!==null){const classified=row.normalEggs+row.brokenEggs+row.dirtyEggs;const variance=classified-row.totalEggs;if(variance!==0)add({fingerprint:`egg-classification:${row.id}`,ruleCode:"EGG_CLASSIFICATION_MISMATCH",domain:"eggs_sales",severity:abs(variance)>=Math.max(30,row.totalEggs*.02)?"high":"medium",title:`Egg classification does not equal output for ${flock?.code??"a flock"}`,explanation:`Classified eggs differ from total output by ${abs(variance)} eggs.`,recommendedAction:"Recount normal, broken, and dirty eggs against the total collection.",...common,expectedValue:row.totalEggs,recordedValue:classified,variance,unit:"eggs",evidence:{dailyRecordId:row.id,totalEggs:row.totalEggs,normalEggs:row.normalEggs,brokenEggs:row.brokenEggs,dirtyEggs:row.dirtyEggs,recordedBy:row.recordedBy}})}
    const official=row.deaths??0;const allocated=mortalityByDay.get(`${row.flockId}:${row.recordDate}`)??0;if(official!==allocated&&(official>0||allocated>0))add({fingerprint:`mortality-allocation:${row.id}`,ruleCode:"MORTALITY_ALLOCATION_MISMATCH",domain:"mortality",severity:allocated>official?"high":"medium",title:`Mortality causes do not reconcile for ${flock?.code??"a flock"}`,explanation:`Daily Records reports ${official} deaths while cause events allocate ${allocated}.`,recommendedAction:"Complete or correct cause events so they equal the official Daily Record total.",...common,expectedValue:official,recordedValue:allocated,variance:allocated-official,unit:"birds",evidence:{dailyRecordId:row.id,officialDeaths:official,allocatedDeaths:allocated,recordedBy:row.recordedBy}});
    const locked=input.operatingDays.find(day=>day.farmId===flock?.farmId&&day.date===row.recordDate&&day.status==="locked"&&day.lockedAt);if(locked?.lockedAt&&Date.parse(row.updatedAt)>Date.parse(locked.lockedAt)&&!input.approvedCorrectionSourceIds.has(row.id))add({fingerprint:`locked-change:${row.id}:${row.updatedAt}`,ruleCode:"LOCKED_RECORD_CHANGED_WITHOUT_APPROVAL",domain:"governance",severity:"critical",title:`A locked Daily Record changed without an approved correction`,explanation:`${flock?.code??"A flock"} was changed after the operating day locked, and no approved correction request references the record.`,recommendedAction:"CEO should review the audit history and require a governed correction explanation.",...common,evidence:{dailyRecordId:row.id,lockedAt:locked.lockedAt,updatedAt:row.updatedAt,recordedBy:row.recordedBy}})
  }

  for(const [flockId,rows] of dailyByFlock){const flock=flockById.get(flockId);for(let index=1;index<rows.length;index++){const prior=rows[index-1],current=rows[index];if(dateDiff(current.recordDate,prior.recordDate)!==1||prior.closingBirds===null||current.openingBirds===null)continue;const variance=current.openingBirds-prior.closingBirds;if(variance!==0)add({fingerprint:`bird-continuity:${current.id}`,ruleCode:"BIRD_DAY_CONTINUITY_BREAK",domain:"birds",severity:meaningful(variance,prior.closingBirds)?"high":"medium",title:`Bird continuity breaks between consecutive days`,explanation:`${flock?.code??"The flock"} opens with ${current.openingBirds} birds after closing the prior day with ${prior.closingBirds}.`,recommendedAction:"Find the missing transfer, loss, or incorrect count before relying on population analytics.",...scope(flock,farmById),recordDate:current.recordDate,expectedValue:prior.closingBirds,recordedValue:current.openingBirds,variance,unit:"birds",evidence:{priorDailyRecordId:prior.id,currentDailyRecordId:current.id,priorDate:prior.recordDate,currentDate:current.recordDate}})}const latest=rows.at(-1);if(flock?.status==="active"&&latest?.closingBirds!==null&&latest?.closingBirds!==undefined&&latest.closingBirds!==flock.currentCount){const variance=flock.currentCount-latest.closingBirds;add({fingerprint:`flock-current:${flock.id}`,ruleCode:"FLOCK_CURRENT_COUNT_MISMATCH",domain:"birds",severity:meaningful(variance,latest.closingBirds)?"high":"medium",title:`Flock master count differs from its latest close`,explanation:`${flock.code} shows ${flock.currentCount} current birds but its latest Daily Record closes at ${latest.closingBirds}.`,recommendedAction:"Reconcile the flock master population through an approved lifecycle correction.",...scope(flock,farmById),recordDate:latest.recordDate,expectedValue:latest.closingBirds,recordedValue:flock.currentCount,variance,unit:"birds",evidence:{dailyRecordId:latest.id,flockId:flock.id}})}}

  const sessionTotals=new Map<string,number>();for(const row of input.sessions)if(row.status==="completed"&&row.actualKg!==null){const key=`${row.flockId}:${row.recordDate}`;sessionTotals.set(key,(sessionTotals.get(key)??0)+row.actualKg)}
  const dailyMap=new Map(input.daily.map(row=>[`${row.flockId}:${row.recordDate}`,row]));const feedLedger=new Map<string,number>();for(const row of input.stock)if(row.sourceKind==="feed_day_close"&&row.sourceKey)feedLedger.set(row.sourceKey,(feedLedger.get(row.sourceKey)??0)+row.quantity);
  for(const closure of input.closures.filter(row=>row.status==="closed")){const flock=flockById.get(closure.flockId);const key=`${closure.flockId}:${closure.recordDate}`;const sessions=round(sessionTotals.get(key)??0);const daily=dailyMap.get(key);const ledger=round(feedLedger.get(key)??0);const common={...scope(flock,farmById),recordDate:closure.recordDate};for(const comparison of [{code:"FEED_SESSION_CLOSE_MISMATCH",label:"feeding sessions",value:sessions},{code:"FEED_DAILY_SYNC_MISMATCH",label:"Daily Record",value:daily?.feedKg??0},{code:"FEED_STOCK_ISSUE_MISMATCH",label:"inventory issue",value:ledger}]){const variance=round(comparison.value-closure.actualKg);if(abs(variance)>.001)add({fingerprint:`${comparison.code.toLowerCase()}:${closure.id}`,ruleCode:comparison.code,domain:"feed",severity:"critical",title:`Closed feed quantity disagrees with ${comparison.label}`,explanation:`${flock?.code??"The flock"} closed at ${closure.actualKg} kg while ${comparison.label} records ${comparison.value} kg.`,recommendedAction:"Reopen and reclose the feeding day after verifying sessions and inventory custody.",...common,expectedValue:closure.actualKg,recordedValue:comparison.value,variance,unit:"kg",estimatedImpactEtb:null,evidence:{closureId:closure.id,dailyRecordId:daily?.id??null,sourceKey:key}})}}

  const conversionMap=new Map(input.conversions.map(row=>[`${row.category}:${row.unit.toLowerCase()}`,row.multiplier]));const producedByFlock=new Map<string,number>();const firstDailyByFlock=new Map<string,string>();for(const row of input.daily){if(row.normalEggs!==null)producedByFlock.set(row.flockId,(producedByFlock.get(row.flockId)??0)+row.normalEggs);if(!firstDailyByFlock.has(row.flockId)||row.recordDate<firstDailyByFlock.get(row.flockId)!)firstDailyByFlock.set(row.flockId,row.recordDate)}const soldByFlock=new Map<string,number>();
  for(const sale of input.sales.filter(row=>row.category==="egg")){const multiplier=conversionMap.get(`egg:${sale.unit.toLowerCase()}`);if(!sale.flockId)add({fingerprint:`egg-sale-scope:${sale.id}`,ruleCode:"EGG_SALE_UNLINKED",domain:"eggs_sales",severity:"medium",title:"Egg sale is not linked to a flock",explanation:`${sale.label} cannot be traced back to production custody.`,recommendedAction:"Link the sale to the producing flock or document a governed allocation.",farmId:sale.farmId,recordDate:sale.saleDate,recordedValue:sale.quantity,unit:sale.unit,estimatedImpactEtb:sale.grossAmount,evidence:{saleId:sale.id,recordedBy:sale.recordedBy,customer:sale.customer}});if(multiplier===undefined)add({fingerprint:`egg-sale-unit:${sale.id}`,ruleCode:"EGG_SALE_UNIT_UNCONVERTED",domain:"eggs_sales",severity:"medium",title:`Egg sale unit “${sale.unit}” has no conversion`,explanation:"Production is recorded in eggs, so this sale cannot be reconciled until its unit conversion is governed.",recommendedAction:"Configure the unit-to-egg multiplier and refresh reconciliation.",flockId:sale.flockId,farmId:sale.farmId,recordDate:sale.saleDate,recordedValue:sale.quantity,unit:sale.unit,estimatedImpactEtb:sale.grossAmount,evidence:{saleId:sale.id,recordedBy:sale.recordedBy}});if(sale.flockId&&multiplier!==undefined)soldByFlock.set(sale.flockId,(soldByFlock.get(sale.flockId)??0)+sale.quantity*multiplier)}
  for(const [flockId,sold] of soldByFlock){const flock=flockById.get(flockId);const first=firstDailyByFlock.get(flockId);const complete=flock&&first&&dateDiff(first,flock.placementDate)<=1;if(!complete){add({fingerprint:`egg-opening-gap:${flockId}`,ruleCode:"EGG_OPENING_BALANCE_UNAVAILABLE",domain:"eggs_sales",severity:"low",title:`Egg custody begins after flock placement`,explanation:`${flock?.code??"The flock"} has sales but production history does not begin at placement, so a trustworthy opening egg balance is unavailable.`,recommendedAction:"Document the opening egg balance before using cumulative sales reconciliation.",...scope(flock,farmById),evidence:{firstDailyDate:first??null,placementDate:flock?.placementDate??null}});continue}const produced=producedByFlock.get(flockId)??0;const variance=round(produced-sold);if(variance<0)add({fingerprint:`egg-negative-balance:${flockId}`,ruleCode:"EGG_SALES_EXCEED_PRODUCTION",domain:"eggs_sales",severity:"critical",title:`Recorded egg sales exceed traceable production`,explanation:`${flock?.code??"The flock"} has sold ${round(sold)} eggs against ${produced} recorded marketable eggs.`,recommendedAction:"Investigate sales, unit conversion, production omissions, and any opening balance evidence.",...scope(flock,farmById),expectedValue:produced,recordedValue:round(sold),variance:round(sold-produced),unit:"eggs",evidence:{flockId,firstDailyDate:first}})}

  for(const count of input.physicalCounts){const variance=round(count.countedQuantity-count.ledgerQuantity);if(abs(variance)>.001){const pct=abs(variance)/(abs(count.ledgerQuantity)||1);const impact=round(abs(variance)*count.unitCost,2);add({fingerprint:`physical-count:${count.id}`,ruleCode:"PHYSICAL_STOCK_VARIANCE",domain:"inventory",severity:pct>=.05||impact>=1000?"high":"medium",title:"Physical stock differs from the system ledger",explanation:`The count differs by ${abs(variance)} units, with an estimated custody impact of ETB ${impact.toLocaleString()}.`,recommendedAction:"Recount, inspect receipts/issues/transfers, then use a reasoned adjustment if confirmed.",warehouseId:count.warehouseId,recordDate:count.countDate,expectedValue:count.ledgerQuantity,recordedValue:count.countedQuantity,variance,unit:"stock units",estimatedImpactEtb:impact,evidence:{physicalCountId:count.id,itemId:count.itemId,countedBy:count.countedBy}})}}
  const adjustmentGroups=new Map<string,StockInput[]>();for(const row of input.stock.filter(row=>row.transactionType==="adjustment")){const key=`${row.warehouseId}:${row.itemId}`;adjustmentGroups.set(key,[...(adjustmentGroups.get(key)??[]),row])}for(const [key,rows] of adjustmentGroups){const impact=rows.reduce((sum,row)=>sum+abs(row.quantity*row.unitCost),0);if(rows.length>=3||impact>=2500){const [warehouseId,itemId]=key.split(":");add({fingerprint:`adjustment-pattern:${key}`,ruleCode:"REPEATED_STOCK_ADJUSTMENTS",domain:"inventory",severity:impact>=5000||rows.length>=5?"high":"medium",title:"Repeated inventory adjustments need review",explanation:`${rows.length} adjustments carry an absolute estimated value of ETB ${round(impact,2).toLocaleString()}.`,recommendedAction:"Compare the adjustments with physical counts, source documents, and the responsible users.",warehouseId,estimatedImpactEtb:round(impact,2),evidence:{itemId,movementIds:rows.map(row=>row.id),recordedBy:[...new Set(rows.map(row=>row.recordedBy).filter(Boolean))]}})}}

  const allocationsByEntry=new Map<string,number>();for(const row of input.costAllocations)allocationsByEntry.set(row.costEntryId,(allocationsByEntry.get(row.costEntryId)??0)+row.amount);for(const entry of input.costEntries){const explicitAllocation=allocationsByEntry.get(entry.id);const directlyScoped=Boolean(entry.farmId||entry.flockId||entry.batchId);const allocated=round(explicitAllocation??(directlyScoped?entry.amount:0),2);const variance=round(allocated-entry.amount,2);if(abs(variance)>.01)add({fingerprint:`cost-allocation:${entry.id}`,ruleCode:"COST_ALLOCATION_MISMATCH",domain:"financial",severity:abs(variance)>=Math.max(1000,entry.amount*.05)?"high":"medium",title:"Cost entry is not fully and uniquely allocated",explanation:`ETB ${entry.amount.toLocaleString()} was recorded while allocations total ETB ${allocated.toLocaleString()}.`,recommendedAction:"Correct allocation scopes or amounts before locking the financial period.",farmId:entry.farmId,flockId:entry.flockId,batchId:entry.batchId,recordDate:entry.entryDate,expectedValue:entry.amount,recordedValue:allocated,variance,unit:"ETB",estimatedImpactEtb:abs(variance),evidence:{description:entry.description,category:entry.category,entryDate:entry.entryDate,amountEtb:entry.amount,allocatedEtb:allocated,allocationMethod:entry.allocationMethod,supplierName:entry.supplierName,invoiceNumber:entry.invoiceNumber,costEntryId:entry.id}})}for(const period of input.costPeriods){const warnings=Array.isArray(period.warnings)?period.warnings.length:0;if(period.status==="locked"&&(period.unallocatedCost>0||warnings>0))add({fingerprint:`locked-cost-warning:${period.id}`,ruleCode:"LOCKED_FINANCIAL_PERIOD_HAS_GAPS",domain:"financial",severity:period.unallocatedCost>=5000?"critical":"high",title:"A locked financial period still contains reconciliation gaps",explanation:`The period has ETB ${period.unallocatedCost.toLocaleString()} unallocated and ${warnings} recorded warning${warnings===1?"":"s"}.`,recommendedAction:"CEO should review the lock evidence and raise a governed correction if necessary.",farmId:period.farmId,flockId:period.flockId,batchId:period.batchId,recordDate:period.periodEnd,recordedValue:period.unallocatedCost,unit:"ETB",estimatedImpactEtb:period.unallocatedCost,evidence:{periodId:period.id,warnings:period.warnings}});if(period.status==="draft"&&period.periodEnd<input.asOfDate.slice(0,7)+"-01")add({fingerprint:`unlocked-cost-period:${period.id}`,ruleCode:"PAST_FINANCIAL_PERIOD_UNLOCKED",domain:"financial",severity:"medium",title:"A past financial period remains unlocked",explanation:`The period ending ${period.periodEnd} can still change and should not be treated as final.`,recommendedAction:"Reconcile costs and revenue, then have the CEO lock the period.",farmId:period.farmId,flockId:period.flockId,batchId:period.batchId,recordDate:period.periodEnd,evidence:{periodId:period.id,status:period.status}})}

  for(const flock of input.flocks.filter(row=>row.status==="active")){const house=houseById.get(flock.houseId),batch=flock.batchId?batchById.get(flock.batchId):undefined;const broken=!farmById.has(flock.farmId)||!house||house.farmId!==flock.farmId||!batch||batch.farmId!==flock.farmId||batch.houseId!==flock.houseId;if(broken)add({fingerprint:`lineage:${flock.id}`,ruleCode:"ACTIVE_FLOCK_LINEAGE_BROKEN",domain:"lineage",severity:"critical",title:`Active flock ${flock.code} has broken lifecycle lineage`,explanation:"Farm, house, batch, and flock ownership do not form one consistent custody chain.",recommendedAction:"Stop lifecycle changes and submit a CEO-approved lineage correction.",...scope(flock,farmById),evidence:{flockCode:flock.code,farmName:farmById.get(flock.farmId)?.name??"Farm record missing",farmRecordFound:farmById.has(flock.farmId),houseRecordFound:Boolean(house),houseMatchesFarm:Boolean(house&&house.farmId===flock.farmId),batchRecordFound:Boolean(batch),batchMatchesFarm:Boolean(batch&&batch.farmId===flock.farmId),batchMatchesHouse:Boolean(batch&&batch.houseId===flock.houseId)}})}
  for(const batch of input.batches.filter(row=>row.status==="active")){const linked=input.flocks.filter(flock=>flock.batchId===batch.id).reduce((sum,flock)=>sum+flock.initialCount,0);if(linked!==batch.totalCount)add({fingerprint:`batch-placement:${batch.id}`,ruleCode:"BATCH_FLOCK_PLACEMENT_MISMATCH",domain:"lineage",severity:abs(linked-batch.totalCount)>=Math.max(5,batch.totalCount*.005)?"high":"medium",title:`Batch ${batch.code} does not reconcile to flock placements`,explanation:`The batch contains ${batch.totalCount} birds while linked flock placements total ${linked}.`,recommendedAction:"Verify the placement split and submit a governed lifecycle correction.",batchId:batch.id,farmId:batch.farmId,houseId:batch.houseId,expectedValue:batch.totalCount,recordedValue:linked,variance:linked-batch.totalCount,unit:"birds",evidence:{batchId:batch.id,flockIds:input.flocks.filter(flock=>flock.batchId===batch.id).map(flock=>flock.id)}})}

  const duplicateSales=new Map<string,SaleInput[]>();for(const sale of input.sales){const key=[sale.saleDate,sale.category,sale.flockId??sale.farmId??"unscoped",sale.label,sale.quantity,sale.unit,sale.grossAmount,sale.customer??""].join("|");duplicateSales.set(key,[...(duplicateSales.get(key)??[]),sale])}for(const rows of duplicateSales.values())if(rows.length>1){const sale=rows[0],flock=sale.flockId?flockById.get(sale.flockId):undefined;add({fingerprint:`possible-duplicate-sale:${rows.map(row=>row.id).sort().join(":")}`,ruleCode:"POSSIBLE_DUPLICATE_SALE",domain:"eggs_sales",severity:"medium",title:"Multiple sales have identical custody details",explanation:`${rows.length} records share the same date, scope, product, quantity, customer, and amount.`,recommendedAction:"Confirm separate source documents or void the duplicate through governance.",...scope(flock,farmById),farmId:flock?.farmId??sale.farmId,recordDate:sale.saleDate,estimatedImpactEtb:sale.grossAmount*(rows.length-1),evidence:{saleIds:rows.map(row=>row.id),recordedBy:[...new Set(rows.map(row=>row.recordedBy).filter(Boolean))]}})}
  return [...findings.values()].sort((a,b)=>severityRank[b.severity]-severityRank[a.severity]||a.domain.localeCompare(b.domain)||a.fingerprint.localeCompare(b.fingerprint));
}

export function summarizeFindings(findings:Array<{severity:ReconciliationSeverity;status:string;domain:ReconciliationDomain;estimatedImpactEtb?:number|null}>){const active=findings.filter(row=>!["resolved","accepted_exception","cleared"].includes(row.status));const weighted=active.reduce((sum,row)=>sum+({critical:20,high:10,medium:4,low:1}[row.severity]),0);return{active:active.length,critical:active.filter(row=>row.severity==="critical").length,high:active.filter(row=>row.severity==="high").length,medium:active.filter(row=>row.severity==="medium").length,low:active.filter(row=>row.severity==="low").length,estimatedImpactEtb:round(active.reduce((sum,row)=>sum+(row.estimatedImpactEtb??0),0),2),trustScore:Math.max(0,Math.round(100-Math.min(100,weighted))),byDomain:Object.fromEntries((["birds","feed","mortality","eggs_sales","inventory","financial","lineage","governance"] as ReconciliationDomain[]).map(domain=>[domain,active.filter(row=>row.domain===domain).length]))};}
