/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import { usePageFilter, ResetPageFilters } from "@/components/page-filter-controls";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import {
  Activity, AlertTriangle, Bird, Building2, CheckCircle2, ChevronRight, ClipboardCheck,
  Egg, Gauge, Home, Map, Plus, RefreshCw, Search, ShieldCheck, Syringe, TrendingDown,
  TrendingUp, Warehouse,
} from "lucide-react";

import { useFarmScope } from "@/components/farm-scope-context";
import type { FarmMonitoringResponse, MonitoringStatus } from "@/lib/farm-monitoring";

function number(value: number | null, suffix = "", places = 1) {
  return value === null ? "Unavailable" : `${value.toLocaleString(undefined, { maximumFractionDigits: places })}${suffix}`;
}

function timeLabel(value: string | null) {
  if (!value) return "No record yet";
  return new Intl.DateTimeFormat("en-ET", { hour: "2-digit", minute: "2-digit" }).format(new Date(value));
}

function statusStyle(status: MonitoringStatus | "pending" | "on_track") {
  if (status === "critical") return "border-ember-500/30 bg-ember-500/10 text-ember-600";
  if (status === "watch") return "border-amber-500/30 bg-amber-500/10 text-amber-700";
  if (status === "data_gap" || status === "pending") return "border-sky-500/30 bg-sky-500/10 text-sky-700";
  if (status === "empty") return "border-sand-200 bg-sand-100 text-forest-600";
  return "border-leaf-500/30 bg-leaf-500/10 text-forest-700";
}

function StatusBadge({ status }: { status: MonitoringStatus | "pending" | "on_track" }) {
  return <span className={`rounded-full border px-2.5 py-1 text-[9px] font-semibold uppercase tracking-[.1em] ${statusStyle(status)}`}>{status.replaceAll("_", " ")}</span>;
}

function Trend({ value }: { value: "up" | "down" | "flat" | "unavailable" }) {
  if (value === "up") return <TrendingUp className="h-4 w-4 text-leaf-600" aria-label="Upward trend"/>;
  if (value === "down") return <TrendingDown className="h-4 w-4 text-ember-500" aria-label="Downward trend"/>;
  return <span className="text-xs text-forest-500">{value === "flat" ? "Stable" : "No trend"}</span>;
}

function LoadingState() {
  return <div className="max-w-full min-w-0 space-y-4 overflow-hidden" aria-label="Loading farm monitoring"><div className="h-52 animate-pulse rounded-2xl bg-forest-900/20"/><div className="h-36 animate-pulse rounded-2xl bg-sand-100"/><div className="grid min-w-0 gap-4 lg:grid-cols-3">{[1,2,3].map((item)=><div key={item} className="h-80 min-w-0 animate-pulse rounded-2xl bg-sand-100"/>)}</div></div>;
}

function FlockPanel({ flock }: { flock: FarmMonitoringResponse["farms"][number]["houses"][number]["flocks"][number] }) {
  const rail = flock.targetAttainment === null ? null : Math.max(2, Math.min(100, flock.targetAttainment / 1.2));
  return <article className="min-w-0 rounded-xl border border-sand-200 bg-white p-4">
    <div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="text-forest-900">{flock.code}</strong><StatusBadge status={flock.status}/></div><p className="mt-1 text-xs capitalize text-forest-500">{flock.type} · week {flock.ageWeeks} · {flock.liveBirds.toLocaleString()} birds</p></div><Trend value={flock.trend}/></div>
    <div className="mt-4 grid min-w-0 gap-4 sm:grid-cols-[1.2fr_.8fr]"><div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-forest-500">{flock.metricLabel}</p><p className="mt-1 text-2xl font-semibold tabular-nums text-forest-900">{number(flock.actual,flock.unit)}</p><p className="text-[11px] text-forest-500">Target {number(flock.target,flock.unit)}</p>{rail===null?<div className="mt-2 h-2 rounded-full bg-sand-100"/>:<div className="relative mt-2 h-2 rounded-full bg-sand-100"><div className={`h-full rounded-full ${flock.status==="critical"?"bg-ember-500":flock.status==="watch"?"bg-amber-500":"bg-leaf-500"}`} style={{width:`${rail}%`}}/><span className="absolute inset-y-[-2px] left-[83.33%] w-px bg-forest-900"/></div>}</div><div className="grid grid-cols-2 gap-2 text-xs"><div><span className="block text-forest-500">Feed / bird</span><strong>{number(flock.feedPerBirdGrams," g")}</strong></div><div><span className="block text-forest-500">Mortality</span><strong>{number(flock.mortalityPct,"%",2)}</strong></div><div><span className="block text-forest-500">Record</span><strong className="capitalize">{flock.recordStatus}</strong></div><div><span className="block text-forest-500">Feed day</span><strong>{flock.feedClosed?"Closed":"Open"}</strong></div></div></div>
    <div className="mt-4 flex min-w-0 flex-wrap items-center justify-between gap-3 border-t border-sand-100 pt-3"><div className="flex items-center gap-3 text-[11px] text-forest-500"><span>Updated {timeLabel(flock.dataUpdatedAt)}</span>{flock.upcomingHealthWork>0?<span className="inline-flex items-center gap-1"><Syringe className="h-3.5 w-3.5"/>{flock.upcomingHealthWork} upcoming</span>:null}</div><div className="flex flex-wrap gap-2"><Link href={`/app/flocks/${flock.id}`} className="inline-flex min-h-10 items-center rounded-lg border border-sand-200 px-3 text-xs font-semibold text-forest-700">Profile</Link><Link href={flock.actionRoute} className="inline-flex min-h-10 items-center gap-1 rounded-lg border border-forest-900/15 px-3 text-xs font-semibold text-forest-800 hover:bg-sand-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-forest-700">{flock.nextAction}<ChevronRight className="h-3.5 w-3.5"/></Link></div></div>
  </article>;
}

function HouseCard({ house, farmId }: { house: FarmMonitoringResponse["farms"][number]["houses"][number]; farmId: string }) {
  return <section className="max-w-full min-w-0 overflow-hidden rounded-2xl border border-sand-200 bg-[#f7f4ed] shadow-sm">
    <div className="flex min-w-0 items-start justify-between gap-3 border-b border-sand-200 p-5"><div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-forest-500">{house.type}</p><Link href={`/app/farms/${farmId}/houses/${house.id}`} className="mt-1 inline-flex items-center gap-1 truncate text-xl font-semibold text-forest-900 hover:underline">{house.name}<ChevronRight className="h-4 w-4"/></Link><p className="mt-1 text-xs text-forest-600">{house.flocks.length} active flock{house.flocks.length===1?"":"s"} · {house.liveBirds.toLocaleString()} birds</p></div><StatusBadge status={house.status}/></div>
    <div className="grid grid-cols-2 border-b border-sand-200 bg-white text-xs sm:grid-cols-4"><div className="p-3"><span className="block text-forest-500">Capacity use</span><strong className="mt-1 block text-base">{number(house.utilizationPct,"%",0)}</strong></div><div className="border-l border-sand-100 p-3"><span className="block text-forest-500">Records</span><strong className="mt-1 block text-base">{house.recordsComplete}/{house.recordsExpected}</strong></div><div className="border-l border-sand-100 p-3"><span className="block text-forest-500">Feed closed</span><strong className="mt-1 block text-base">{house.feedDaysClosed}/{house.feedDaysExpected}</strong></div><div className="border-l border-sand-100 p-3"><span className="block text-forest-500">Health work</span><strong className="mt-1 block text-base">{house.upcomingHealthWork}</strong></div></div>
    {house.flocks.length?<div className="grid min-w-0 gap-3 p-4">{house.flocks.map((flock)=><FlockPanel key={flock.id} flock={flock}/>)}</div>:<div className="p-5"><div className="rounded-xl border border-dashed border-sand-300 bg-white p-5 text-center"><Home className="mx-auto h-6 w-6 text-forest-400"/><p className="mt-2 text-sm font-semibold text-forest-900">House is currently empty</p><p className="mt-1 text-xs text-forest-600">No active flock is assigned to this house.</p><Link href={`/app/flocks/new?farm_id=${farmId}&house_id=${house.id}`} className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-lg bg-forest-900 px-3 text-xs font-semibold text-white"><Plus className="h-3.5 w-3.5"/>Place a flock</Link></div></div>}
  </section>;
}

export function FarmMonitoringControlRoom() {
  const { role, branches } = useFarmScope();
  const [data,setData]=useState<FarmMonitoringResponse|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [branchId,setBranchId]=usePageFilter<string>("branchId", ""); const [query,setQuery]=usePageFilter<string>("query", ""); const [selectedFarmId,setSelectedFarmId]=usePageFilter<string>("selectedFarmId", "");
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError(null);const params=new URLSearchParams({branch_id:branchId});const response=await fetch(`/api/farm-monitoring/dashboard?${params}`,{signal,cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body?.error??"Could not load farm monitoring.");setData(body as FarmMonitoringResponse);setLoading(false);},[branchId]);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal).catch((reason:unknown)=>{if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"Could not load farm monitoring.");setLoading(false);});return()=>controller.abort();},[load]);
  const visibleFarms=useMemo(()=>{const value=query.trim().toLowerCase();return data?.farms.filter((farm)=>!value||farm.name.toLowerCase().includes(value)||farm.branchName.toLowerCase().includes(value))??[];},[data,query]);
  useEffect(()=>{if(!visibleFarms.length){setSelectedFarmId("");return;}if(!visibleFarms.some((farm)=>farm.id===selectedFarmId))setSelectedFarmId(visibleFarms[0].id);},[selectedFarmId,visibleFarms,setSelectedFarmId]);
  const selectedFarm=visibleFarms.find((farm)=>farm.id===selectedFarmId)??null;
  if(loading&&!data)return <LoadingState/>;
  return <main className="max-w-full min-w-0 space-y-5 overflow-x-hidden">
      <div className="flex justify-end"><ResetPageFilters /></div>
    <section className="relative max-w-full min-w-0 overflow-hidden rounded-2xl bg-forest-900 p-5 text-white shadow-sm sm:p-6"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full border-[38px] border-leaf-500/15"/><div className="relative flex min-w-0 flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div className="min-w-0"><p className="text-[11px] font-semibold uppercase tracking-[.24em] text-leaf-300">Farm watchtower · {data?.meta.today}</p><h1 className="mt-2 font-display text-3xl font-semibold">See the whole farm from one place</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-sand-100">Move from farm to house to flock without losing the operational picture. Attention signals rise first; missing data never appears as zero.</p><div className="mt-4 flex flex-wrap gap-4 text-xs text-sand-100"><span>{data?.meta.scopeLabel}</span><span>Latest record {timeLabel(data?.meta.latestRecordAt??null)}</span><span>Addis Ababa time</span></div></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>void load().catch((reason:unknown)=>setError(reason instanceof Error?reason.message:"Refresh failed."))} disabled={loading} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-4 text-sm font-semibold hover:bg-white/15 disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin motion-reduce:animate-none":""}`}/>Refresh</button>{role&&role!=="farm_manager"?<Link href="/app/ceo/setup" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-semibold text-forest-900"><Plus className="h-4 w-4"/>Manage structure</Link>:null}</div></div>
      <div className="relative mt-5 grid min-w-0 gap-3 border-t border-white/15 pt-5 md:grid-cols-2">{role!=="farm_manager"?<label className="grid gap-1 text-xs text-sand-100">Branch<select value={branchId} onChange={(event)=>setBranchId(event.target.value)} className="min-h-11 rounded-xl border border-white/20 bg-white/10 px-3 text-white outline-none focus:ring-2 focus:ring-leaf-300"><option className="text-forest-900" value="">All branches</option>{branches.map((branch)=><option className="text-forest-900" key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label>:null}<label className="grid gap-1 text-xs text-sand-100">Find a farm<div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-sand-100"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Farm or branch name" className="min-h-11 w-full rounded-xl border border-white/20 bg-white/10 pl-9 pr-3 text-white outline-none placeholder:text-white/50 focus:ring-2 focus:ring-leaf-300"/></div></label></div>
    </section>
    {error?<div role="alert" className="rounded-xl border border-ember-500/30 bg-ember-500/10 p-4 text-sm text-ember-700">{error}<button type="button" onClick={()=>void load()} className="ml-2 font-semibold underline">Retry</button></div>:null}
    {data?<>
      <section aria-label="Farm monitoring summary" className="grid max-w-full min-w-0 overflow-hidden rounded-2xl border border-sand-200 bg-white shadow-sm sm:grid-cols-2 xl:grid-cols-6">{([
        ["Assigned farms",number(data.summary.farms,"",0),`${data.summary.houses} houses`,Map],
        ["Live birds",number(data.summary.liveBirds,"",0),`${data.summary.activeFlocks} active flocks`,Bird],
        ["Capacity use",number(data.summary.capacityUtilizationPct,"%",0),`${data.summary.operatingHouses} houses operating`,Gauge],
        ["Today HDEP",number(data.summary.todayHdep,"%",1),"Layer and parent stock",Egg],
        ["Mortality",number(data.summary.mortalityPct,"%",2),"Today’s recorded bird-days",Activity],
        ["Needs attention",number(data.summary.housesNeedingAttention,"",0),`${data.summary.emptyHouses} empty houses`,AlertTriangle],
      ] as const).map(([label,value,note,Icon],index)=><article key={label} className={`min-w-0 p-4 ${index?"border-t border-sand-200 sm:border-l sm:border-t-0":""}`}><Icon className="h-4 w-4 text-forest-500"/><p className="mt-3 text-[10px] font-semibold uppercase tracking-[.14em] text-forest-500">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums text-forest-900">{value}</p><p className="mt-1 text-[11px] text-forest-600">{note}</p></article>)}</section>
      <section className="max-w-full min-w-0 overflow-hidden rounded-2xl border border-sand-200 bg-white shadow-sm [contain:inline-size]"><div className="border-b border-sand-200 bg-[#f2eee4] p-5"><p className="text-[11px] font-semibold uppercase tracking-[.2em] text-forest-500">Assigned farm horizon</p><h2 className="mt-1 font-display text-2xl font-semibold text-forest-900">Choose a farm to inspect</h2><p className="mt-1 text-sm text-forest-600">Farms needing attention are placed first.</p></div>{visibleFarms.length?<div className="w-full max-w-full min-w-0 overflow-x-auto overscroll-x-contain p-4"><div className="flex w-max gap-3">{visibleFarms.map((farm)=><button key={farm.id} type="button" onClick={()=>setSelectedFarmId(farm.id)} aria-pressed={selectedFarmId===farm.id} className={`w-[280px] shrink-0 rounded-xl border p-4 text-left transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-forest-700 ${selectedFarmId===farm.id?"border-forest-700 bg-forest-900 text-white shadow-md":"border-sand-200 bg-white text-forest-900 hover:border-forest-300"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-[10px] uppercase tracking-[.14em] ${selectedFarmId===farm.id?"text-sand-100":"text-forest-500"}`}>{farm.branchName}</p><strong className="mt-1 block text-lg">{farm.name}</strong></div><StatusBadge status={farm.status}/></div><div className={`mt-4 grid grid-cols-3 gap-2 border-t pt-3 text-xs ${selectedFarmId===farm.id?"border-white/15":"border-sand-100"}`}><div><span className="block opacity-65">Birds</span><strong>{farm.liveBirds.toLocaleString()}</strong></div><div><span className="block opacity-65">Houses</span><strong>{farm.operatingHouses}/{farm.houseCount}</strong></div><div><span className="block opacity-65">Records</span><strong>{farm.recordsComplete}/{farm.recordsExpected}</strong></div></div></button>)}</div></div>:<div className="p-8 text-center text-sm text-forest-600">No farms match the current filter.</div>}</section>
      {selectedFarm?<section className="max-w-full min-w-0 space-y-4"><div className="max-w-full min-w-0 overflow-hidden rounded-2xl border border-sand-200 bg-white shadow-sm"><div className="grid min-w-0 gap-5 p-5 lg:grid-cols-[1fr_auto]"><div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-forest-500">Selected farm · {selectedFarm.branchName}</p><div className="mt-1 flex flex-wrap items-center gap-3"><h2 className="font-display text-3xl font-semibold text-forest-900">{selectedFarm.name}</h2><StatusBadge status={selectedFarm.status}/></div><p className="mt-2 text-sm text-forest-600">{selectedFarm.operatingHouses} of {selectedFarm.houseCount} houses operating · {selectedFarm.activeFlocks} active flocks · {selectedFarm.liveBirds.toLocaleString()} live birds</p><div className="mt-4 h-2 max-w-xl rounded-full bg-sand-100"><div className="h-full rounded-full bg-leaf-500" style={{width:`${Math.min(100,selectedFarm.utilizationPct??0)}%`}}/></div><p className="mt-1 text-[11px] text-forest-500">Capacity utilization {number(selectedFarm.utilizationPct,"%",0)}</p></div><div className="grid grid-cols-2 gap-2 text-xs sm:grid-cols-4 lg:min-w-[420px]"><div className="rounded-xl bg-sand-50 p-3"><span className="text-forest-500">HDEP</span><strong className="mt-1 block text-lg">{number(selectedFarm.hdep,"%")}</strong></div><div className="rounded-xl bg-sand-50 p-3"><span className="text-forest-500">Feed / bird</span><strong className="mt-1 block text-lg">{number(selectedFarm.feedPerBirdGrams," g")}</strong></div><div className="rounded-xl bg-sand-50 p-3"><span className="text-forest-500">Mortality</span><strong className="mt-1 block text-lg">{number(selectedFarm.mortalityPct,"%",2)}</strong></div><div className="rounded-xl bg-sand-50 p-3"><span className="text-forest-500">Health work</span><strong className="mt-1 block text-lg">{selectedFarm.upcomingHealthWork}</strong></div></div></div></div>
        <div className="flex justify-end"><Link href={`/app/farms/${selectedFarm.id}`} className="inline-flex min-h-10 items-center gap-1 rounded-xl border border-sand-200 bg-white px-4 text-sm font-semibold text-forest-700">Open full farm profile<ChevronRight className="h-4 w-4"/></Link></div>{selectedFarm.houses.length?<div className="grid max-w-full min-w-0 gap-4 xl:grid-cols-2">{selectedFarm.houses.map((house)=><HouseCard key={house.id} house={house} farmId={selectedFarm.id}/>)}</div>:<div className="rounded-2xl border border-dashed border-sand-300 bg-sand-50 p-8 text-center"><Warehouse className="mx-auto h-7 w-7 text-forest-400"/><p className="mt-2 font-semibold text-forest-900">No houses configured</p><p className="mt-1 text-sm text-forest-600">Add houses before placing flocks in this farm.</p></div>}
      </section>:null}
      <div className="grid max-w-full min-w-0 gap-4 xl:grid-cols-[minmax(0,.9fr)_minmax(0,1.1fr)]"><section className="max-w-full min-w-0 overflow-hidden rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ClipboardCheck className="h-5 w-5 text-forest-600"/><h2 className="text-lg font-semibold text-forest-900">Immediate work queue</h2></div><div className="mt-4 space-y-2">{data.actions.length?data.actions.slice(0,10).map((action)=><Link key={action.id} href={action.route} className="flex min-h-14 min-w-0 gap-3 rounded-xl border border-sand-200 p-3 hover:bg-sand-50"><span className={`mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full ${action.severity==="critical"?"bg-ember-500":action.severity==="warning"?"bg-amber-500":"bg-sky-500"}`}/><span className="min-w-0"><strong className="block text-sm text-forest-900">{action.title}</strong><span className="mt-0.5 block text-xs text-forest-600">{action.context}</span></span></Link>):<div className="flex gap-2 rounded-xl bg-leaf-500/10 p-4 text-sm text-forest-700"><CheckCircle2 className="h-5 w-5 shrink-0"/>No immediate farm-monitoring exceptions.</div>}</div></section><section className="max-w-full min-w-0 overflow-hidden rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-forest-600"/><h2 className="text-lg font-semibold text-forest-900">Monitoring confidence</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-sand-50 p-4"><span className="text-xs text-forest-500">Daily Records</span><strong className="mt-1 block text-xl">{number(data.dataTrust.recordCoveragePct,"%",0)}</strong></div><div className="rounded-xl bg-sand-50 p-4"><span className="text-xs text-forest-500">Feed closed</span><strong className="mt-1 block text-xl">{number(data.dataTrust.feedClosurePct,"%",0)}</strong></div><div className="rounded-xl bg-sand-50 p-4"><span className="text-xs text-forest-500">Targets available</span><strong className="mt-1 block text-xl">{number(data.dataTrust.targetCoveragePct,"%",0)}</strong></div></div><ul className="mt-4 space-y-2 text-xs text-forest-600">{data.dataTrust.notes.map((note)=><li key={note} className="flex gap-2"><Building2 className="mt-0.5 h-3.5 w-3.5 shrink-0"/>{note}</li>)}</ul></section></div>
    </>:null}
  </main>;
}
