/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2f3e700bbe08ec3650831db1e3b9b7c9)
interface __BaseEnv_Env {
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	APP_ENVIRONMENT: "staging" | "production";
	APP_BASE_URL: "https://ethio-poultry-app-staging.walidmurad65.workers.dev" | "https://ethio-poultry-app.walidmurad65.workers.dev";
	NEXT_PUBLIC_SUPABASE_URL: "https://uzmhpecehmlwojdmitgj.supabase.co" | "https://gnmeoxwqexennoidwwpf.supabase.co";
	SUPABASE_PROJECT_REF: "uzmhpecehmlwojdmitgj" | "gnmeoxwqexennoidwwpf";
	RECONCILIATION_AI_ENABLED?: "true";
	GROQ_MODEL?: "openai/gpt-oss-120b";
	NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	ADMIN_ACCESS_CODE: string;
	GROQ_API_KEY?: string;
	MONITORING_INGEST_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface StagingEnv {
		EMAIL: SendEmail;
		ASSETS: Fetcher;
		APP_ENVIRONMENT: "staging";
		APP_BASE_URL: "https://ethio-poultry-app-staging.walidmurad65.workers.dev";
		NEXT_PUBLIC_SUPABASE_URL: "https://uzmhpecehmlwojdmitgj.supabase.co";
		SUPABASE_PROJECT_REF: "uzmhpecehmlwojdmitgj";
		RECONCILIATION_AI_ENABLED: "true";
		GROQ_MODEL: "openai/gpt-oss-120b";
		NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
		SUPABASE_SERVICE_ROLE_KEY: string;
		ADMIN_ACCESS_CODE: string;
		GROQ_API_KEY: string;
		MONITORING_INGEST_TOKEN: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENVIRONMENT" | "APP_BASE_URL" | "NEXT_PUBLIC_SUPABASE_URL" | "SUPABASE_PROJECT_REF" | "RECONCILIATION_AI_ENABLED" | "GROQ_MODEL" | "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY" | "SUPABASE_SERVICE_ROLE_KEY" | "ADMIN_ACCESS_CODE" | "GROQ_API_KEY" | "MONITORING_INGEST_TOKEN">> {}
}
