"use client";

import { ArrowRight, CheckCircle2, ClipboardCheck, RefreshCw, Scale, ShieldCheck } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Finding = {
  id: string; rule_code: string; domain: string; severity: "critical"|"high"|"medium"|"low";
  status: string; title: string; explanation: string; recommended_action: string; finding_date: string|null;
  expected_value: unknown; recorded_value: unknown; variance_value: number|null; variance_unit: string|null;
  evidence: unknown; farm_name: string|null; house_name: string|null; flock_code: string|null;
  warehouse_name: string|null; estimated_impact_etb: number|null; first_seen_at: string; last_seen_at: string;
  responses: Array<{id:string;action:string;note:string;actor_name:string|null;created_at:string}>;
};
type Dashboard = {
  meta:{role:string;asOfDate:string;refreshedAt:string;canResolve:boolean;canOperate:boolean};
  summary:{active:number;critical:number;high:number;medium:number;low:number;trustScore:number;estimatedImpactEtb:number;byDomain:Record<string,number>};
  findings:Finding[]; hotspots:Array<{id:string;label:string;count:number}>;
  options:{warehouses:Array<{id:string;name:string}>;items:Array<{id:string;name:string;unit:string}>};
};

const domains = ["all","birds","feed","mortality","eggs_sales","inventory","financial","lineage","governance"];
const activeStatuses = new Set(["open","acknowledged","investigating"]);
const severityStyle = {critical:"bg-ember-600 text-white",high:"bg-ember-500/10 text-ember-700",medium:"bg-amber-500/15 text-amber-800",low:"bg-sky-500/10 text-sky-700"};
const domainLabel = (value:string) => value.replaceAll("_"," ").replace(/\b\w/g, letter => letter.toUpperCase());
const showValue = (value:unknown) => value === null || value === undefined ? "Unavailable" : typeof value === "object" ? JSON.stringify(value) : String(value);

export default function ReconciliationPage(){
  const [data,setData]=useState<Dashboard|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [domain,setDomain]=useState("all"); const [status,setStatus]=useState("active"); const [query,setQuery]=useState("");
  const [busy,setBusy]=useState("");
  const selected=data&&typeof window!=="undefined"?new URLSearchParams(window.location.search).get("finding")??"":"";
  const load=useCallback(async(force=false)=>{setLoading(true);setError("");try{const response=await fetch(`/api/reconciliation${force?"?refresh=1":""}`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body?.error??"Could not load reconciliation findings.");setData(body)}catch(value){setError(value instanceof Error?value.message:"Could not load reconciliation findings.")}finally{setLoading(false)}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const findings=useMemo(()=>data?.findings.filter(item=>(domain==="all"||item.domain===domain)&&(status==="all"||(status==="active"?activeStatuses.has(item.status):item.status===status))&&(!query||`${item.title} ${item.rule_code} ${item.farm_name} ${item.flock_code} ${item.warehouse_name}`.toLowerCase().includes(query.toLowerCase())))??[],[data,domain,status,query]);
  useEffect(()=>{if(selected){document.getElementById(`finding-${selected}`)?.scrollIntoView({behavior:"smooth",block:"center"})}},[findings,selected]);
  const act=async(finding:Finding,action:string)=>{const note=window.prompt(action==="accept_exception"?"Document why this is an accepted exception (minimum 8 characters):":"Enter the evidence-based response note (minimum 8 characters):")?.trim();if(!note)return;setBusy(finding.id);try{const response=await fetch(`/api/reconciliation/findings/${finding.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,note,evidence:[]})});const body=await response.json();if(!response.ok)throw new Error(body?.error??"Could not update finding.");await load()}catch(value){window.alert(value instanceof Error?value.message:"Could not update finding.")}finally{setBusy("")}};
  if(loading&&!data)return <div className="grid min-h-[55vh] place-items-center text-forest-600"><RefreshCw className="h-6 w-6 animate-spin" aria-hidden="true"/><span className="sr-only">Loading reconciliation evidence</span></div>;
  if(error&&!data)return <div className="rounded-2xl border border-ember-300 bg-ember-50 p-6 text-ember-800"><strong>Reconciliation could not load.</strong><p className="mt-2 text-sm">{error}</p><button onClick={()=>void load()} className="mt-4 rounded-xl bg-forest-900 px-4 py-2 text-sm font-semibold text-white">Try again</button></div>;
  if(!data)return null;
  return <main className="space-y-5 pb-12">
    <section className="relative overflow-hidden rounded-[1.75rem] bg-forest-900 px-5 py-7 text-white shadow-sm sm:px-8 sm:py-9">
      <div className="absolute -right-12 -top-20 h-56 w-56 rounded-full border-[34px] border-amber-400/10"/><div className="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-end">
        <div className="max-w-3xl"><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.22em] text-amber-300"><ShieldCheck className="h-4 w-4"/>Operational proof desk</p><h2 className="mt-3 font-display text-3xl font-semibold leading-tight sm:text-4xl">Trust the operation because every ledger agrees.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-sand-100/80">Independent checks connect bird movement, feed, eggs, sales, stock and costs. A finding is evidence of a mismatch or missing proof—not an accusation of intent.</p></div>
        <div className="flex flex-wrap items-center gap-3"><div className="rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-xs"><span className="block text-sand-200">Evidence as of</span><strong className="mt-1 block text-sm">{data.meta.asOfDate}</strong></div><button onClick={()=>void load(true)} disabled={loading} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-white px-4 text-sm font-semibold text-forest-900 disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Run checks now</button></div>
      </div>
    </section>

    <section className="grid overflow-hidden rounded-2xl border border-sand-200 bg-white shadow-sm sm:grid-cols-2 xl:grid-cols-5">
      <Metric label="Trust score" value={`${data.summary.trustScore}/100`} note="Weighted evidence confidence" tone="text-forest-800"/>
      <Metric label="Active findings" value={String(data.summary.active)} note="Require review or proof" tone="text-forest-900"/>
      <Metric label="Critical" value={String(data.summary.critical)} note="Immediate governance attention" tone="text-ember-600"/>
      <Metric label="High" value={String(data.summary.high)} note="Material operating variance" tone="text-amber-700"/>
      <Metric label="Estimated exposure" value={`${data.summary.estimatedImpactEtb.toLocaleString()} ETB`} note="Estimate, not booked loss" tone="text-forest-900"/>
    </section>

    <section className="rounded-2xl border border-sand-200 bg-white p-5 shadow-sm">
      <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-forest-500">Control coverage</p><h2 className="mt-1 font-display text-2xl font-semibold text-forest-900">Where the records disagree</h2></div><div className="grid gap-2 sm:grid-cols-3"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search flock, farm, rule…" className="min-h-11 rounded-xl border border-sand-300 px-3 text-sm outline-none focus:ring-2 focus:ring-forest-600"/><select value={domain} onChange={event=>setDomain(event.target.value)} className="min-h-11 rounded-xl border border-sand-300 px-3 text-sm">{domains.map(item=><option key={item} value={item}>{domainLabel(item)}</option>)}</select><select value={status} onChange={event=>setStatus(event.target.value)} className="min-h-11 rounded-xl border border-sand-300 px-3 text-sm"><option value="active">Active only</option><option value="all">All statuses</option><option value="resolved">Resolved</option><option value="accepted_exception">Accepted exceptions</option></select></div></div>
      <div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{domains.slice(1).map(item=><button key={item} onClick={()=>setDomain(item)} className={`rounded-xl border p-3 text-left transition ${domain===item?"border-forest-700 bg-forest-900 text-white":"border-sand-200 bg-sand-50 text-forest-800 hover:border-forest-300"}`}><span className="block text-[10px] uppercase tracking-wider opacity-70">{domainLabel(item)}</span><strong className="mt-1 block text-xl">{data.summary.byDomain[item]??0}</strong></button>)}</div>
    </section>

    <section className="space-y-3" aria-label="Reconciliation findings">
      <div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-forest-500">Evidence chain</p><h2 className="mt-1 font-display text-2xl font-semibold text-forest-900">{findings.length} findings in this view</h2></div><span className="hidden text-xs text-forest-500 sm:block">Expected → recorded → variance → action</span></div>
      {findings.length?findings.map(finding=><article id={`finding-${finding.id}`} key={finding.id} className={`overflow-hidden rounded-2xl border bg-white shadow-sm ${selected===finding.id?"border-amber-500 ring-2 ring-amber-300/40":"border-sand-200"}`}>
        <div className="grid gap-5 p-5 xl:grid-cols-[1.25fr_1fr_auto] xl:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider ${severityStyle[finding.severity]}`}>{finding.severity}</span><span className="rounded-full bg-sand-100 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-forest-600">{domainLabel(finding.domain)}</span><span className="text-[10px] font-semibold uppercase tracking-wider text-forest-400">{finding.rule_code}</span></div><h3 className="mt-3 text-lg font-semibold text-forest-900">{finding.title}</h3><p className="mt-1 text-sm leading-6 text-forest-600">{finding.explanation}</p><p className="mt-2 text-xs font-medium text-forest-700">{[finding.farm_name,finding.house_name,finding.flock_code,finding.warehouse_name,finding.finding_date].filter(Boolean).join(" · ")||"Organization-wide control"}</p></div>
          <div className="grid grid-cols-[1fr_auto_1fr_auto_1fr] items-center gap-2 rounded-xl bg-sand-50 p-3 text-center"><Proof label="Expected" value={showValue(finding.expected_value)}/><ArrowRight className="h-4 w-4 text-forest-300"/><Proof label="Recorded" value={showValue(finding.recorded_value)}/><ArrowRight className="h-4 w-4 text-forest-300"/><Proof label="Variance" value={finding.variance_value===null?"Evidence gap":`${finding.variance_value.toLocaleString()} ${finding.variance_unit??""}`}/></div>
          <div className="min-w-44 xl:text-right"><span className="rounded-full border border-sand-200 px-3 py-1 text-xs font-semibold text-forest-700">{domainLabel(finding.status)}</span>{finding.estimated_impact_etb?<p className="mt-3 text-xs text-forest-500">Estimated exposure<br/><strong className="text-base text-forest-900">{finding.estimated_impact_etb.toLocaleString()} ETB</strong></p>:null}</div></div>
        <details className="border-t border-sand-200"><summary className="cursor-pointer px-5 py-3 text-sm font-semibold text-forest-700 hover:bg-sand-50">Inspect source evidence and response history</summary><div className="grid gap-4 border-t border-sand-100 bg-sand-50/60 p-5 lg:grid-cols-2"><div><h4 className="text-xs font-semibold uppercase tracking-wider text-forest-500">Source evidence</h4><pre className="mt-2 max-h-52 overflow-auto whitespace-pre-wrap rounded-xl bg-forest-950 p-3 text-xs leading-5 text-sand-100">{JSON.stringify(finding.evidence,null,2)}</pre></div><div><h4 className="text-xs font-semibold uppercase tracking-wider text-forest-500">Required action</h4><p className="mt-2 text-sm leading-6 text-forest-700">{finding.recommended_action}</p><div className="mt-3 space-y-2">{finding.responses?.length?finding.responses.map(response=><div key={response.id} className="rounded-lg border border-sand-200 bg-white p-3 text-xs"><strong>{domainLabel(response.action)}</strong> by {response.actor_name??"authorized user"}<p className="mt-1 text-forest-600">{response.note}</p></div>):<p className="text-xs text-forest-500">No response has been recorded.</p>}</div></div></div></details>
        <div className="flex flex-wrap items-center gap-2 border-t border-sand-200 px-5 py-3"><span className="mr-auto text-xs text-forest-500">A note is mandatory. Resolution does not alter the underlying source record.</span>{activeStatuses.has(finding.status)?<><Action label="Acknowledge" onClick={()=>void act(finding,"acknowledge")} disabled={busy===finding.id}/><Action label="Investigate" onClick={()=>void act(finding,"investigate")} disabled={busy===finding.id}/>{data.meta.role==="farm_manager"?<Action label="Add explanation" onClick={()=>void act(finding,"explain")} disabled={busy===finding.id}/>:null}{data.meta.canResolve?<><Action label="Accept exception" onClick={()=>void act(finding,"accept_exception")} disabled={busy===finding.id}/><Action label="Resolve after correction" primary onClick={()=>void act(finding,"resolve")} disabled={busy===finding.id}/></>:null}</>:data.meta.canResolve?<Action label="Reopen" onClick={()=>void act(finding,"reopen")} disabled={busy===finding.id}/>:null}</div>
      </article>):<div className="rounded-2xl border border-leaf-300 bg-leaf-50 p-8 text-center text-forest-800"><CheckCircle2 className="mx-auto h-8 w-8"/><h3 className="mt-3 font-semibold">No findings match this view.</h3><p className="mt-1 text-sm">This means the selected controls currently agree; it does not replace physical verification.</p></div>}
    </section>
    {data.meta.canOperate?<PhysicalCount data={data} onSaved={()=>load(true)}/>:null}
  </main>
}

function Metric({label,value,note,tone}:{label:string;value:string;note:string;tone:string}){return <div className="border-b border-sand-200 p-5 last:border-b-0 sm:border-r xl:border-b-0"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-forest-500">{label}</p><strong className={`mt-2 block font-display text-2xl ${tone}`}>{value}</strong><p className="mt-1 text-xs text-forest-500">{note}</p></div>}
function Proof({label,value}:{label:string;value:string}){return <div className="min-w-0"><span className="block text-[9px] font-semibold uppercase tracking-wider text-forest-400">{label}</span><strong className="mt-1 block break-words text-xs text-forest-900">{value}</strong></div>}
function Action({label,onClick,disabled,primary=false}:{label:string;onClick:()=>void;disabled:boolean;primary?:boolean}){return <button onClick={onClick} disabled={disabled} className={`min-h-9 rounded-lg px-3 text-xs font-semibold disabled:opacity-50 ${primary?"bg-forest-900 text-white":"border border-sand-300 bg-white text-forest-800 hover:bg-sand-50"}`}>{label}</button>}
function PhysicalCount({data,onSaved}:{data:Dashboard;onSaved:()=>Promise<void>}){const [warehouseId,setWarehouse]=useState(data.options.warehouses[0]?.id??"");const [itemId,setItem]=useState(data.options.items[0]?.id??"");const [quantity,setQuantity]=useState("");const [notes,setNotes]=useState("");const [saving,setSaving]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);try{const response=await fetch("/api/reconciliation/physical-counts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({warehouseId,itemId,countDate:data.meta.asOfDate,countedQuantity:Number(quantity),notes,evidence:[]})});const body=await response.json();if(!response.ok)throw new Error(body?.error??"Could not save physical count.");setQuantity("");setNotes("");await onSaved()}catch(value){window.alert(value instanceof Error?value.message:"Could not save physical count.")}finally{setSaving(false)}};return <section className="rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-leaf-500/10 text-forest-700"><Scale className="h-5 w-5"/></span><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-forest-500">Independent verification</p><h2 className="mt-1 font-display text-2xl font-semibold text-forest-900">Record a physical stock count</h2><p className="mt-1 text-sm text-forest-600">The system snapshots the ledger balance and calculates the unexplained variance automatically.</p></div></div><form onSubmit={event=>void submit(event)} className="mt-5 grid gap-3 lg:grid-cols-[1fr_1fr_.7fr_1.5fr_auto]"><select required value={warehouseId} onChange={event=>setWarehouse(event.target.value)} className="min-h-11 rounded-xl border border-sand-300 px-3 text-sm"><option value="">Select warehouse</option>{data.options.warehouses.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select required value={itemId} onChange={event=>setItem(event.target.value)} className="min-h-11 rounded-xl border border-sand-300 px-3 text-sm"><option value="">Select item</option>{data.options.items.map(item=><option key={item.id} value={item.id}>{item.name} ({item.unit})</option>)}</select><input required type="number" min="0" step="any" value={quantity} onChange={event=>setQuantity(event.target.value)} placeholder="Counted quantity" className="min-h-11 rounded-xl border border-sand-300 px-3 text-sm"/><input value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Count circumstances or witness" className="min-h-11 rounded-xl border border-sand-300 px-3 text-sm"/><button disabled={saving} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-forest-900 px-4 text-sm font-semibold text-white disabled:opacity-50"><ClipboardCheck className="h-4 w-4"/>{saving?"Recording…":"Record count"}</button></form></section>}
