/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import { useCallback, useEffect, useState } from "react";
import { Check, Clock3, FileCheck2, RefreshCw, ShieldAlert, ShieldX, X } from "lucide-react";

type RequestRow = { id:string;request_type:string;status:string;reason:string;requested_at:string;decision_note?:string|null;proposed_values?:unknown };
type BreakGlassRow = { id:string;status:string;reason:string;ticket_reference:string;requested_minutes:number;requested_at:string;session?:{id:string;expires_at:string;revoked_at:string|null;is_active:boolean}|null };
type AuditRow = { id:number;event_type:string;entity_table:string|null;reason:string|null;occurred_at:string;actor_role:string|null };
const types=["batch_create","batch_archive","flock_place","flock_transfer","flock_close","flock_archive","feed_template","breed_target","health_schedule","warning_threshold","locked_correction","void_record"];

export default function GovernancePage(){
  const [role,setRole]=useState<string|null>(null);const [requests,setRequests]=useState<RequestRow[]>([]);const [support,setSupport]=useState<BreakGlassRow[]>([]);const [audit,setAudit]=useState<AuditRow[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  const load=useCallback(async()=>{setLoading(true);setMessage("");const context=await fetch("/api/me/context",{cache:"no-store"}).then(r=>r.json());setRole(context?.role??null);const [requestRes,auditRes,supportRes]=await Promise.all([fetch("/api/governance/requests",{cache:"no-store"}),fetch("/api/governance/audit",{cache:"no-store"}),context?.role==="ceo"?fetch("/api/governance/break-glass",{cache:"no-store"}):Promise.resolve(null)]);if(requestRes.ok)setRequests((await requestRes.json()).requests??[]);if(auditRes.ok)setAudit((await auditRes.json()).events??[]);if(supportRes?.ok)setSupport((await supportRes.json()).requests??[]);setLoading(false)},[]);
  useEffect(()=>{void load()},[load]);
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);let proposed:unknown={};try{proposed=JSON.parse(String(form.get("proposed_values")||"{}"))}catch{setMessage("Proposed values must be valid JSON.");return}const response=await fetch("/api/governance/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({request_type:form.get("request_type"),reason:form.get("reason"),farm_id:form.get("farm_id")||null,source_table:form.get("source_table")||null,source_id:form.get("source_id")||null,source_version:form.get("source_version")||null,proposed_values:proposed,changed_fields:Object.keys((proposed&&typeof proposed==="object"?proposed:{}) as object)})});const data=await response.json();setMessage(response.ok?"Request submitted for CEO review.":data.error??"Unable to submit request.");if(response.ok){event.currentTarget.reset();await load()}};
  const decide=async(id:string,decision:"approved"|"rejected",supportRequest=false)=>{const note=window.prompt(`Decision note for ${decision}:`);if(!note)return;const path=supportRequest?`/api/governance/break-glass/${id}/decision`:`/api/governance/requests/${id}/decision`;const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision,note})});const data=await response.json();setMessage(response.ok?`Request ${decision}.`:data.error??"Decision failed.");await load()};
  const revokeSupport=async(row:BreakGlassRow)=>{if(!row.session)return;const reason=window.prompt(`Why should support session ${row.ticket_reference} end now?`)?.trim();if(!reason)return;const response=await fetch(`/api/governance/break-glass/sessions/${row.session.id}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason})});const data=await response.json();setMessage(response.ok?"Support access revoked immediately.":data.error??"Support access could not be revoked.");await load()};
  return <main className="space-y-6 pb-10"><section className="overflow-hidden rounded-[28px] bg-forest-900 p-7 text-white"><p className="text-[10px] font-semibold uppercase tracking-[.24em] text-amber-300">Separation of duties</p><h1 className="mt-2 font-display text-3xl font-semibold">Governance control desk</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-sand-100/80">Operational changes are proposed by farm managers, decided by the CEO, version checked, and retained in an append-only decision history.</p><button onClick={()=>void load()} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-white/20 px-4 py-2 text-sm"><RefreshCw className="h-4 w-4"/>Refresh</button></section>
  {message?<p role="status" className="rounded-xl border border-sand-200 bg-white p-3 text-sm text-forest-800">{message}</p>:null}
  {role==="farm_manager"?<section className="rounded-2xl border border-sand-200 bg-white p-5"><h2 className="font-display text-2xl text-forest-900">Submit controlled change</h2><form onSubmit={submit} className="mt-4 grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-sm">Request type<select name="request_type" required className="h-11 rounded-xl border border-sand-200 px-3">{types.map(t=><option key={t} value={t}>{t.replaceAll("_"," ")}</option>)}</select></label><label className="grid gap-1 text-sm">Farm ID (when scoped)<input name="farm_id" className="h-11 rounded-xl border border-sand-200 px-3"/></label><label className="grid gap-1 text-sm md:col-span-2">Reason<textarea name="reason" required minLength={8} className="min-h-20 rounded-xl border border-sand-200 p-3"/></label><label className="grid gap-1 text-sm md:col-span-2">Proposed values (JSON)<textarea name="proposed_values" defaultValue="{}" className="min-h-28 rounded-xl border border-sand-200 p-3 font-mono text-xs"/></label><input type="hidden" name="source_table"/><input type="hidden" name="source_id"/><input type="hidden" name="source_version"/><button className="h-11 rounded-xl bg-forest-900 px-5 text-sm font-semibold text-white">Submit proposal</button></form></section>:null}
  {role==="ceo"&&support.some(r=>r.status==="pending")?<section className="rounded-2xl border border-ember-300 bg-ember-50 p-5"><div className="flex gap-3"><ShieldAlert className="h-5 w-5 text-ember-600"/><div><h2 className="font-semibold text-forest-900">Support access awaiting decision</h2><p className="text-sm text-forest-600">Approval grants one administrator full, audited tenant access for at most four hours.</p></div></div>{support.filter(r=>r.status==="pending").map(r=><div key={r.id} className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-white p-4"><div><p className="font-semibold">{r.ticket_reference} · {r.requested_minutes} minutes</p><p className="text-sm text-forest-600">{r.reason}</p></div><div className="flex gap-2"><button onClick={()=>void decide(r.id,"approved",true)} className="rounded-lg bg-forest-900 px-3 py-2 text-xs font-semibold text-white">Approve</button><button onClick={()=>void decide(r.id,"rejected",true)} className="rounded-lg border px-3 py-2 text-xs font-semibold">Reject</button></div></div>)}</section>:null}
  {role==="ceo"&&support.some(r=>r.status==="approved"&&r.session?.is_active)?<section className="rounded-2xl border border-ember-300 bg-white p-5"><div className="flex items-start gap-3"><ShieldX className="h-5 w-5 text-ember-600"/><div><h2 className="font-semibold text-forest-900">Active support custody</h2><p className="text-sm text-forest-600">End access immediately when the approved work is complete or its purpose changes.</p></div></div><div className="mt-4 space-y-2">{support.filter(r=>r.status==="approved"&&r.session?.is_active).map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-ember-50 p-4"><div><p className="font-semibold text-forest-900">{r.ticket_reference}</p><p className="text-xs text-forest-600">Expires {new Date(r.session!.expires_at).toLocaleString()}</p></div><button type="button" onClick={()=>void revokeSupport(r)} className="min-h-10 rounded-xl bg-ember-600 px-4 text-xs font-semibold text-white">Revoke access</button></div>)}</div></section>:null}
  <section className="rounded-2xl border border-sand-200 bg-white"><div className="border-b border-sand-200 p-5"><h2 className="font-display text-2xl text-forest-900">Change requests</h2><p className="text-sm text-forest-600">{loading?"Loading…":`${requests.length} requests in scope`}</p></div><div className="divide-y divide-sand-200">{requests.length===0?<p className="p-5 text-sm text-forest-600">No governance requests yet.</p>:requests.map(r=><article key={r.id} className="flex flex-wrap items-start justify-between gap-4 p-5"><div><div className="flex items-center gap-2"><FileCheck2 className="h-4 w-4"/><p className="font-semibold capitalize">{r.request_type.replaceAll("_"," ")}</p><span className="rounded-full bg-sand-100 px-2 py-1 text-[10px] uppercase">{r.status}</span></div><p className="mt-2 max-w-2xl text-sm text-forest-600">{r.reason}</p><p className="mt-1 text-xs text-forest-500">{new Date(r.requested_at).toLocaleString()}</p></div>{role==="ceo"&&r.status==="pending"?<div className="flex gap-2"><button aria-label="Approve request" onClick={()=>void decide(r.id,"approved")} className="grid h-9 w-9 place-items-center rounded-lg bg-leaf-500 text-white"><Check className="h-4 w-4"/></button><button aria-label="Reject request" onClick={()=>void decide(r.id,"rejected")} className="grid h-9 w-9 place-items-center rounded-lg bg-ember-500 text-white"><X className="h-4 w-4"/></button></div>:null}</article>)}</div></section>
  <section className="rounded-2xl border border-sand-200 bg-white p-5"><h2 className="flex items-center gap-2 font-display text-2xl text-forest-900"><Clock3 className="h-5 w-5"/>Audit history</h2><div className="mt-4 space-y-2">{audit.length===0?<p className="text-sm text-forest-600">No audit events in this scope.</p>:audit.slice(0,50).map(a=><div key={a.id} className="grid gap-1 rounded-xl bg-sand-50 p-3 text-sm md:grid-cols-[1fr_180px]"><div><p className="font-semibold">{a.event_type}</p><p className="text-xs text-forest-600">{a.entity_table??"Governance"}{a.reason?` · ${a.reason}`:""}</p></div><p className="text-xs text-forest-500 md:text-right">{new Date(a.occurred_at).toLocaleString()}</p></div>)}</div></section></main>
}
