"use client";

import { CheckCircle2, Clock3, Loader2, Play, Send, UserCheck, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";

import type { ReconciliationResolution } from "@/lib/reconciliation-resolution-contract";

const statusLabel: Record<string, string> = { open: "Ready to assign", assigned: "Assigned", acknowledged: "Acknowledged", in_progress: "Work in progress", awaiting_verification: "Waiting for CEO verification", escalated: "Overdue", resolved: "Verified and closed" };
const tomorrow = () => { const date = new Date(Date.now() + 24 * 3600000); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); };

export function ReconciliationAssignmentPanel({ findingId, findingStatus, role, onChanged }: { findingId: string; findingStatus: string; role: string; onChanged: () => Promise<unknown> }) {
  const [data, setData] = useState<ReconciliationResolution | null>(null);
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [note, setNote] = useState(""); const [evidence, setEvidence] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/reconciliation/findings/${findingId}/resolution`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not load resolution workflow."); setData(body); }, [findingId]);
  useEffect(() => {
    const controller = new AbortController();
    void fetch(`/api/reconciliation/findings/${findingId}/resolution`, { cache: "no-store", signal: controller.signal })
      .then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not load resolution workflow."); return body; })
      .then(body => setData(body))
      .catch(value => { if (!(value instanceof DOMException && value.name === "AbortError")) setError(value instanceof Error ? value.message : "Could not load assignment."); });
    return () => controller.abort();
  }, [findingId, findingStatus]);

  const transition = async (body: Record<string, unknown>) => { if (!data?.action) return; setBusy(true); setError(""); try { const response = await fetch(`/api/alerts/actions/${data.action.actionId}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Task could not be updated."); setNote(""); setEvidence(""); await load(); await onChanged(); } catch (value) { setError(value instanceof Error ? value.message : "Task could not be updated."); } finally { setBusy(false); } };
  const assign = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(""); try { const due = String(form.get("dueAt")); const response = await fetch(`/api/reconciliation/findings/${findingId}/assignment`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ownerId: form.get("ownerId"), dueAt: new Date(due).toISOString(), instruction: form.get("instruction") }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Follow-up could not be assigned."); setOpen(false); await load(); await onChanged(); } catch (value) { setError(value instanceof Error ? value.message : "Follow-up could not be assigned."); } finally { setBusy(false); } };

  if (!data && !error) return <div className="flex items-center gap-2 border-t border-sand-200 px-5 py-3 text-xs text-forest-500"><Loader2 className="h-4 w-4 animate-spin"/>Loading responsibility…</div>;
  return <section className="border-t border-sand-200 bg-sand-50/70 p-5" aria-label="Assigned resolution workflow">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="mr-auto"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-forest-500">Accountable follow-up</p><p className="mt-1 text-sm font-semibold text-forest-950">{data?.action ? `${statusLabel[data.action.status] ?? data.action.status}${data.action.ownerName ? ` · ${data.action.ownerName}` : ""}` : "No Farm Manager has been assigned"}</p>{data?.action ? <p className="mt-1 flex items-center gap-1 text-xs text-forest-600"><Clock3 className="h-3.5 w-3.5"/>Due {new Date(data.action.dueAt).toLocaleString()}</p> : <p className="mt-1 text-xs text-forest-600">Assign only when accountable follow-up is needed.</p>}</div>
      <div className="flex flex-wrap gap-2">{role === "ceo" && data?.canAssign ? <button type="button" onClick={() => setOpen(true)} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-forest-800 bg-white px-4 text-xs font-semibold text-forest-900"><UserCheck className="h-4 w-4"/>{data.action?.ownerId ? "Reassign follow-up" : "Assign follow-up"}</button> : null}{data?.action && role === "farm_manager" && data.canWork && data.action.status === "assigned" ? <button disabled={busy} onClick={() => void transition({ command: "acknowledge", note: "I have reviewed the assigned Record Check and accept responsibility." })} className="min-h-10 rounded-xl bg-forest-900 px-4 text-xs font-semibold text-white">Acknowledge</button> : null}{data?.action && role === "farm_manager" && data.canWork && ["acknowledged", "escalated"].includes(data.action.status) ? <button disabled={busy} onClick={() => void transition({ command: "start", note: "I started reviewing the highlighted source record." })} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-forest-900 px-4 text-xs font-semibold text-white"><Play className="h-3.5 w-3.5"/>Start work</button> : null}{data?.action && role === "ceo" && data.action.status === "awaiting_verification" ? <button disabled={busy} onClick={() => void transition({ command: "verify" })} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-forest-900 px-4 text-xs font-semibold text-white"><CheckCircle2 className="h-4 w-4"/>Verify and close</button> : null}</div>
    </div>
    {data?.action && role === "farm_manager" && data.canWork && ["assigned", "acknowledged", "in_progress", "escalated"].includes(data.action.status) ? <div className="mt-4 grid gap-3 rounded-xl border border-sand-200 bg-white p-4 lg:grid-cols-[1fr_1fr_auto]"><label className="text-xs font-semibold text-forest-700">What did you correct?<textarea value={note} onChange={event => setNote(event.target.value)} rows={2} className="mt-1 w-full rounded-lg border border-sand-300 p-2 font-normal" placeholder="Describe the exact source record and value corrected."/></label><label className="text-xs font-semibold text-forest-700">Evidence or reference <span className="font-normal">(optional)</span><textarea value={evidence} onChange={event => setEvidence(event.target.value)} rows={2} className="mt-1 w-full rounded-lg border border-sand-300 p-2 font-normal" placeholder="Receipt, count sheet, or approval reference."/></label><button disabled={busy || note.trim().length < 8} onClick={() => void transition({ command: "submit_resolution", note: note.trim(), evidence: evidence.trim() || undefined })} className="inline-flex min-h-11 items-center justify-center gap-2 self-end rounded-xl bg-forest-900 px-4 text-xs font-semibold text-white disabled:opacity-50"><Send className="h-3.5 w-3.5"/>Complete and send to CEO</button></div> : null}
    {data?.action?.sourceCorrected && data.action.status !== "resolved" ? <p className="mt-3 rounded-lg border border-leaf-300 bg-leaf-50 p-3 text-xs font-semibold text-forest-800">The deterministic check is clear. The assigned manager must submit completion, then the CEO verifies the task.</p> : null}
    {error ? <p role="alert" className="mt-3 text-xs font-semibold text-ember-700">{error}</p> : null}
    {open && data ? <div className="fixed inset-0 z-[210] grid place-items-center bg-forest-950/65 p-4" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setOpen(false); }}><form onSubmit={event => void assign(event)} className="w-full max-w-xl overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-start justify-between bg-forest-900 p-5 text-white"><div><p className="text-[10px] font-semibold uppercase tracking-wider text-amber-300">CEO assignment</p><h2 className="mt-1 font-display text-2xl font-semibold">Assign this exact Record Check</h2><p className="mt-2 text-xs text-sand-200">{data.title} · {data.scopeLabel}</p></div><button type="button" onClick={() => setOpen(false)} aria-label="Close" className="grid h-9 w-9 place-items-center rounded-lg border border-white/20"><X className="h-4 w-4"/></button></header><div className="grid gap-4 p-5"><label className="text-sm font-semibold text-forest-900">Farm Manager<select name="ownerId" required defaultValue={data.action?.ownerId ?? ""} className="mt-2 h-11 w-full rounded-xl border border-sand-300 px-3 font-normal"><option value="">Choose an eligible Farm Manager</option>{data.eligibleOwners.map(owner => <option key={owner.id} value={owner.id}>{owner.name} · {owner.scope}</option>)}</select></label><label className="text-sm font-semibold text-forest-900">Due date and time<input name="dueAt" type="datetime-local" required defaultValue={tomorrow()} className="mt-2 h-11 w-full rounded-xl border border-sand-300 px-3 font-normal"/></label><label className="text-sm font-semibold text-forest-900">Work instruction<textarea name="instruction" required minLength={8} defaultValue={data.correction.instruction} rows={4} className="mt-2 w-full rounded-xl border border-sand-300 p-3 font-normal"/></label></div><footer className="flex justify-end gap-2 border-t border-sand-200 p-4"><button type="button" onClick={() => setOpen(false)} className="h-10 rounded-xl border border-sand-300 px-4 text-xs font-semibold">Cancel</button><button disabled={busy || !data.eligibleOwners.length} className="h-10 rounded-xl bg-forest-900 px-4 text-xs font-semibold text-white disabled:opacity-50">{busy ? "Assigning…" : "Assign and notify"}</button></footer></form></div> : null}
  </section>;
}
