import {accessJson,canAccessFarm,getAccessContext,governanceAdmin,isAccessResponse} from "@/lib/access-context";

const DATE=/^\d{4}-\d{2}-\d{2}$/;
export async function POST(request:Request){
  const ctx=await getAccessContext({tenant:true});if(isAccessResponse(ctx))return ctx;if(ctx.role!=="farm_manager"&&!ctx.supportSessionId)return accessJson({error:"Only an assigned farm manager can record health evidence."},403);
  const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const flockId=String(body?.flock_id??"");const eventDate=String(body?.event_date??"");const eventType=String(body?.event_type??"observation");if(!flockId||!DATE.test(eventDate)||!["disease","treatment","observation"].includes(eventType))return accessJson({error:"Flock, date, and a valid event type are required."},400);
  const {data:flock}=await governanceAdmin.from("flocks").select("farm_id").eq("id",flockId).eq("org_id",ctx.orgId).maybeSingle();if(!flock||!(await canAccessFarm(ctx,String(flock.farm_id))))return accessJson({error:"Active farm assignment is required."},403);
  if(!ctx.supportSessionId){const {data:operatingDay}=await governanceAdmin.from("farm_operating_days").select("status").eq("farm_id",flock.farm_id).eq("operating_date",eventDate).maybeSingle();if(operatingDay?.status==="locked")return accessJson({error:"This operating day is locked. Submit a governed correction request instead."},423);}
  const vetName=String(body?.external_veterinarian_name??"").trim();const recommendation=String(body?.veterinarian_recommendation??"").trim();const reference=String(body?.veterinarian_reference??"").trim();const attachment=String(body?.attachment_url??"").trim();const recommendationStatus=String(body?.recommendation_status??"").trim();const hasVetEvidence=Boolean(vetName||recommendation||reference||attachment||recommendationStatus);if(hasVetEvidence&&(!vetName||!recommendation))return accessJson({error:"Veterinarian name and recommendation are required when external guidance is recorded."},400);if(recommendationStatus&&!["received","planned","implemented","declined"].includes(recommendationStatus))return accessJson({error:"Invalid recommendation status."},400);if(recommendationStatus==="declined"&&String(body?.treatment??"").trim().length<8)return accessJson({error:"Declined guidance requires an explanation in the action taken field."},400);
  const row={org_id:ctx.orgId,flock_id:flockId,event_date:eventDate,event_type:eventType,description:String(body?.description??"").trim()||null,diagnosis:String(body?.diagnosis??"").trim()||null,treatment:String(body?.treatment??"").trim()||null,attachment_url:attachment||null,vet_id:ctx.userId,external_veterinarian_name:vetName||null,veterinarian_recommendation:recommendation||null,veterinarian_reference:reference||null,veterinarian_attachment:attachment?{url:attachment}:null,recommendation_status:recommendationStatus||null};
  const {data,error}=await governanceAdmin.from("health_events").insert(row).select("*").single();if(error)return accessJson({error:error.message},400);await governanceAdmin.from("governance_audit_events").insert({org_id:ctx.orgId,actor_id:ctx.userId,actor_role:ctx.role,support_session_id:ctx.supportSessionId,event_type:"health_evidence.recorded",entity_table:"health_events",entity_id:data.id,after_values:data});return accessJson({event:data},201);
}
