/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, ArrowLeft, ArrowRight, Bird, CheckCircle2, ClipboardCheck, Egg, Gauge, HeartPulse, Loader2, PackageCheck, RefreshCw, ShieldAlert, Warehouse } from "lucide-react";

import { useFarmScope } from "@/components/farm-scope-context";
import type { FarmMonitoringResponse, MonitoringStatus } from "@/lib/farm-monitoring";

type Mode="farm"|"houses"|"house"|"flock";
const statusLabel:Record<MonitoringStatus|"critical"|"watch"|"pending"|"on_track",string>={critical:"Critical",watch:"Needs attention",data_gap:"Data gap",empty:"No active flock",on_track:"On track",pending:"Pending"};
function Badge({status}:{status:keyof typeof statusLabel}){const tone=status==="critical"?"bg-red-100 text-red-700":status==="watch"?"bg-amber-100 text-amber-800":status==="data_gap"||status==="pending"?"bg-sky-100 text-sky-700":status==="empty"?"bg-sand-100 text-forest-600":"bg-green-50 text-forest-700";return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide ${tone}`}>{statusLabel[status]}</span>}
function value(number:number|null,suffix="",digits=1){return number===null?"Unavailable":`${number.toLocaleString(undefined,{maximumFractionDigits:digits})}${suffix}`}

export function OperationsDetailWorkspace({mode,farmId,houseId,flockId}:{mode:Mode;farmId?:string;houseId?:string;flockId?:string}){
  const {flocks:scopeFlocks}=useFarmScope();const [data,setData]=useState<FarmMonitoringResponse|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/farm-monitoring/dashboard");const json=await response.json();if(!response.ok)throw new Error(json?.error??"Could not load operational detail.");setData(json as FarmMonitoringResponse)}catch(value){setError(value instanceof Error?value.message:"Could not load operational detail.")}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const farm=useMemo(()=>data?.farms.find((item)=>item.id===farmId||(houseId&&item.houses.some((house)=>house.id===houseId))||(flockId&&item.houses.some((house)=>house.flocks.some((flock)=>flock.id===flockId))))??null,[data,farmId,flockId,houseId]);
  const house=useMemo(()=>farm?.houses.find((item)=>item.id===houseId||(flockId&&item.flocks.some((flock)=>flock.id===flockId)))??null,[farm,flockId,houseId]);
  const flock=useMemo(()=>house?.flocks.find((item)=>item.id===flockId)??null,[flockId,house]);
  const scopedFlock=scopeFlocks.find((item)=>item.id===flockId);
  if(loading)return <div className="grid min-h-[55vh] place-items-center"><div className="text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-forest-600"/><p className="mt-3 text-sm text-forest-600">Building operational profile…</p></div></div>;
  if(error)return <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error}<button type="button" onClick={()=>void load()} className="ml-3 font-semibold underline">Retry</button></div>;
  if(!farm&&mode!=="flock")return <Empty title="Farm not available" text="This farm is outside the current organization scope or no longer exists." href="/app/farms"/>;
  if(mode==="flock"&&!flock)return <Empty title={scopedFlock?.flock_code??"Flock profile unavailable"} text={scopedFlock?"This flock is not active, so it is excluded from today’s operating comparison. Its historical records remain available in Daily Records.":"This flock is outside the current organization scope or no longer exists."} href="/app/flocks"/>;
  if(mode==="house"&&!house)return <Empty title="House not available" text="This house is outside the selected farm or no longer exists." href={farm?`/app/farms/${farm.id}/houses`:"/app/farms"}/>;
  if(mode==="flock"&&flock&&house&&farm)return <FlockView farm={farm} house={house} flock={flock} refresh={load}/>;
  if(mode==="house"&&house&&farm)return <HouseView farm={farm} house={house} refresh={load}/>;
  if(farm)return <FarmView farm={farm} housesOnly={mode==="houses"} refresh={load}/>;
  return null;
}

type Farm=FarmMonitoringResponse["farms"][number];type House=Farm["houses"][number];type Flock=House["flocks"][number];
function Hero({eyebrow,title,text,back,refresh,badge}:{eyebrow:string;title:string;text:string;back:string;refresh:()=>Promise<void>;badge?:React.ReactNode}){return <section className="relative overflow-hidden rounded-[28px] bg-forest-900 px-6 py-7 text-sand-50 sm:px-8 lg:px-10"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full border-[44px] border-amber-500/10"/><div className="relative"><Link href={back} className="inline-flex items-center gap-1 text-xs font-semibold text-sand-100/80 hover:text-white"><ArrowLeft className="h-4 w-4"/>Back</Link><div className="mt-5 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-amber-500">{eyebrow}</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="font-display text-3xl font-semibold sm:text-4xl">{title}</h1>{badge}</div><p className="mt-2 max-w-2xl text-sm leading-6 text-sand-100/80">{text}</p></div><button type="button" onClick={()=>void refresh()} className="inline-flex h-11 items-center gap-2 self-start rounded-xl border border-white/20 px-4 text-sm font-semibold hover:bg-white/10"><RefreshCw className="h-4 w-4"/>Refresh</button></div></div></section>}
function FarmView({farm,housesOnly,refresh}:{farm:Farm;housesOnly:boolean;refresh:()=>Promise<void>}){return <main className="space-y-5 pb-8"><Hero eyebrow={`${farm.branchName} · ${housesOnly?"House network":"Farm profile"}`} title={farm.name} text={`${farm.operatingHouses} of ${farm.houseCount} houses operating with ${farm.activeFlocks} active flocks and ${farm.liveBirds.toLocaleString()} live birds.`} back="/app/farms" refresh={refresh} badge={<Badge status={farm.status}/>}/><MetricStrip values={[["Live birds",farm.liveBirds,Bird],["Capacity used",farm.utilizationPct===null?null:`${value(farm.utilizationPct,"%")}`,Gauge],["Today HDEP",farm.hdep===null?null:value(farm.hdep,"%"),Egg],["Mortality",farm.mortalityPct===null?null:value(farm.mortalityPct,"%",2),Activity],["Health work",farm.upcomingHealthWork,HeartPulse]]}/><section className="rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><div className="flex items-end justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-forest-500">House control board</p><h2 className="mt-1 font-display text-2xl font-semibold text-forest-900">{housesOnly?"Every house in this farm":"Operating houses"}</h2></div><Link href={`/app/farms/${farm.id}/houses`} className="text-sm font-semibold text-forest-700 underline">House view</Link></div><div className="mt-5 grid gap-4 xl:grid-cols-2">{farm.houses.map((house)=><HouseCard key={house.id} farm={farm} house={house}/>)}</div></section><Trust farm={farm}/></main>}
function HouseCard({farm,house}:{farm:Farm;house:House}){return <Link href={`/app/farms/${farm.id}/houses/${house.id}`} className="group rounded-2xl border border-sand-200 p-5 transition hover:border-forest-400 hover:bg-sand-50"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.16em] text-forest-500">{house.type}</p><h3 className="mt-1 text-lg font-semibold text-forest-900">{house.name}</h3></div><Badge status={house.status}/></div><div className="mt-4 grid grid-cols-3 gap-3 border-t border-sand-100 pt-4 text-xs"><div><span className="text-forest-500">Birds</span><strong className="mt-1 block text-base text-forest-900">{house.liveBirds.toLocaleString()}</strong></div><div><span className="text-forest-500">Records</span><strong className="mt-1 block text-base text-forest-900">{house.recordsComplete}/{house.recordsExpected}</strong></div><div><span className="text-forest-500">Feed closed</span><strong className="mt-1 block text-base text-forest-900">{house.feedDaysClosed}/{house.feedDaysExpected}</strong></div></div><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-forest-700">Open house<ArrowRight className="h-4 w-4 transition group-hover:translate-x-0.5"/></span></Link>}
function HouseView({farm,house,refresh}:{farm:Farm;house:House;refresh:()=>Promise<void>}){return <main className="space-y-5 pb-8"><Hero eyebrow={`${farm.name} · ${house.type}`} title={house.name} text={`${house.flocks.length} active flocks, ${house.liveBirds.toLocaleString()} live birds, and ${house.upcomingHealthWork} upcoming health actions.`} back={`/app/farms/${farm.id}/houses`} refresh={refresh} badge={<Badge status={house.status}/>}/><MetricStrip values={[["Live birds",house.liveBirds,Bird],["Capacity",house.capacity===null?null:house.capacity,Warehouse],["Utilization",house.utilizationPct===null?null:value(house.utilizationPct,"%"),Gauge],["Records",`${house.recordsComplete}/${house.recordsExpected}`,ClipboardCheck],["Feed closed",`${house.feedDaysClosed}/${house.feedDaysExpected}`,PackageCheck]]}/><section className="overflow-hidden rounded-2xl border border-sand-200 bg-white shadow-sm"><div className="border-b border-sand-200 p-5"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-forest-500">Current occupants</p><h2 className="mt-1 font-display text-2xl font-semibold text-forest-900">Flock operating picture</h2></div>{house.flocks.length?<div className="divide-y divide-sand-100">{house.flocks.map((flock)=><FlockRow key={flock.id} flock={flock}/>)}</div>:<div className="p-10 text-center text-sm text-forest-600">This house has no active flock.</div>}</section></main>}
function FlockRow({flock}:{flock:Flock}){return <Link href={`/app/flocks/${flock.id}`} className="grid gap-3 p-5 transition hover:bg-sand-50 sm:grid-cols-[1.2fr_repeat(4,1fr)_auto] sm:items-center"><div><strong className="text-forest-900">{flock.code}</strong><p className="text-xs capitalize text-forest-500">{flock.type} · week {flock.ageWeeks}</p></div><Small label={flock.metricLabel} value={value(flock.actual,flock.unit)}/><Small label="Feed / bird" value={value(flock.feedPerBirdGrams," g")}/><Small label="Mortality" value={value(flock.mortalityPct,"%",2)}/><Small label="Birds" value={flock.liveBirds.toLocaleString()}/><Badge status={flock.status}/></Link>}
function FlockView({farm,house,flock,refresh}:{farm:Farm;house:House;flock:Flock;refresh:()=>Promise<void>}){return <main className="space-y-5 pb-8"><Hero eyebrow={`${farm.name} · ${house.name} · ${flock.type}`} title={flock.code} text={`Week ${flock.ageWeeks} with ${flock.liveBirds.toLocaleString()} live birds. ${flock.nextAction}`} back="/app/flocks" refresh={refresh} badge={<Badge status={flock.status}/>}/><MetricStrip values={[[flock.metricLabel,value(flock.actual,flock.unit),Egg],["Target",value(flock.target,flock.unit),Gauge],["Feed / bird",value(flock.feedPerBirdGrams," g"),PackageCheck],["Mortality",value(flock.mortalityPct,"%",2),Activity],["Marketable",value(flock.marketableRate,"%"),CheckCircle2]]}/><div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-sand-200 bg-white p-6 shadow-sm"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-forest-500">Today’s evidence</p><h2 className="mt-1 font-display text-2xl font-semibold text-forest-900">Production readiness</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><Signal label="Daily record" value={flock.recordStatus} good={flock.recordStatus==="complete"}/><Signal label="Feed day" value={flock.feedClosed?"Closed":"Open"} good={flock.feedClosed}/><Signal label="Target attainment" value={value(flock.targetAttainment,"%")} good={(flock.targetAttainment??0)>=95}/><Signal label="Uniformity" value={value(flock.uniformityPct,"%")} good={(flock.uniformityPct??0)>=80}/></div></section><section className="rounded-2xl border border-sand-200 bg-forest-900 p-6 text-sand-50"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-amber-500">Next management action</p><h2 className="mt-2 font-display text-2xl font-semibold">{flock.nextAction}</h2><p className="mt-2 text-sm text-sand-100/80">Use the operating source below to correct today’s evidence or investigate the exception.</p><Link href={flock.actionRoute} className="mt-5 inline-flex h-11 items-center gap-2 rounded-xl bg-sand-50 px-4 text-sm font-semibold text-forest-900">Open action source<ArrowRight className="h-4 w-4"/></Link></section></div><section className="rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><h2 className="font-display text-xl font-semibold text-forest-900">Related operational records</h2><div className="mt-4 flex flex-wrap gap-2"><Link href="/app/daily-records" className="rounded-xl border border-sand-200 px-4 py-2.5 text-sm font-semibold text-forest-700">Daily Records</Link><Link href="/app/feeding-log" className="rounded-xl border border-sand-200 px-4 py-2.5 text-sm font-semibold text-forest-700">Feed Control</Link><Link href="/app/mortality" className="rounded-xl border border-sand-200 px-4 py-2.5 text-sm font-semibold text-forest-700">Mortality</Link><Link href="/app/health" className="rounded-xl border border-sand-200 px-4 py-2.5 text-sm font-semibold text-forest-700">Health Log</Link></div></section></main>}
function MetricStrip({values}:{values:Array<[string,string|number|null,React.ElementType]>}){return <section className="overflow-hidden rounded-2xl border border-sand-200 bg-white shadow-sm"><div className="grid divide-y divide-sand-200 sm:grid-cols-2 sm:divide-x sm:divide-y-0 xl:grid-cols-5">{values.map(([label,metric,Icon])=><div key={label} className="p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-[.17em] text-forest-500">{label}</p><Icon className="h-4 w-4 text-forest-500"/></div><p className="mt-2 font-display text-2xl font-semibold text-forest-900">{metric===null?"Unavailable":metric}</p></div>)}</div></section>}
function Trust({farm}:{farm:Farm}){const record=farm.recordsExpected?farm.recordsComplete/farm.recordsExpected*100:null;const feed=farm.feedDaysExpected?farm.feedDaysClosed/farm.feedDaysExpected*100:null;return <section className="rounded-2xl border border-sand-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-forest-600"/><h2 className="font-display text-xl font-semibold text-forest-900">Decision confidence</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Small label="Record coverage" value={value(record,"%",0)}/><Small label="Feed closure" value={value(feed,"%",0)}/><Small label="Upcoming health work" value={String(farm.upcomingHealthWork)}/></div></section>}
function Small({label,value:display}:{label:string;value:string}){return <div><p className="text-xs text-forest-500">{label}</p><p className="mt-1 font-semibold text-forest-900">{display}</p></div>}
function Signal({label,value:display,good}:{label:string;value:string;good:boolean}){return <div className="rounded-xl bg-sand-50 p-4"><p className="text-xs text-forest-500">{label}</p><div className="mt-1 flex items-center justify-between gap-2"><strong className="capitalize text-forest-900">{display}</strong><span className={`h-2.5 w-2.5 rounded-full ${good?"bg-leaf-500":"bg-amber-500"}`}/></div></div>}
function Empty({title,text,href}:{title:string;text:string;href:string}){return <div className="rounded-[28px] border border-sand-200 bg-white p-10 text-center shadow-sm"><Warehouse className="mx-auto h-8 w-8 text-forest-500"/><h1 className="mt-3 font-display text-3xl font-semibold text-forest-900">{title}</h1><p className="mx-auto mt-2 max-w-xl text-sm text-forest-600">{text}</p><Link href={href} className="mt-5 inline-flex h-11 items-center rounded-xl bg-forest-900 px-4 text-sm font-semibold text-white">Return to operations</Link></div>}
