-- History marker for the original production migration 0002_ops.
-- Its resulting schema is captured by supabase/migration-baseline.json.
-- Never execute this marker as a substitute for bootstrapping an empty database.
